// packages/components-vue/src/atoms/indicators/Badge.vue
<script setup lang="ts">
/**
 * Badge (Atom)
 *
 * A notification indicator with smart overflow logic.
 * Displays notification counts with context-aware capping rules.
 *
 * Data Attributes (Animation Contract):
 * - data-badge: Root element (discovery)
 * - data-count: Raw count value
 * - data-context: Badge context ('default' | 'inbox')
 * - data-state: Badge state
 * - data-badge-text: Text content element
 *
 * Usage:
 * <Badge :count="5" />
 * <Badge :count="150" context="inbox" type="inbox" />
 *
 * @see packages/css/src/components/badge.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { BadgeType, BadgeState, BadgeContext } from '../../types/badge'

interface BadgeProps {
  count: number
  context?: BadgeContext
  type?: BadgeType
  state?: BadgeState
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<BadgeProps>(), {
  count: 0,
  context: 'default',
  type: 'neutral',
  state: 'default'
})

function getBadgeDisplay(count: number, context: BadgeContext): string | null {
  if (count <= 0) return null

  if (context === 'inbox') {
    if (count >= 50) return '+50'
    return count.toString()
  }

  if (count > 99) return '99+'
  return count.toString()
}

const displayValue = computed(() => getBadgeDisplay(props.count, props.context))

const ariaLabel = computed(
  () => `${props.count} ${props.count === 1 ? 'notification' : 'notifications'}`
)

const badgeClasses = computed(() => [
  'badge',
  `badge--${props.type}`,
  `badge--${props.state}`,
  props.class
])
</script>

<template>
  <span
    v-if="displayValue"
    :class="badgeClasses"
    data-badge
    :data-count="count"
    :data-context="context"
    :data-state="state"
    role="status"
    :aria-label="ariaLabel"
  >
    <span class="badge__text" data-badge-text>
      {{ displayValue }}
    </span>
  </span>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/atoms/Badge.tsx
/**
 * Badge (Notification Badge)
 *
 * A notification indicator with smart overflow logic.
 * Displays notification counts with context-aware capping rules.
 *
 * Performance optimizations:
 * - Pure function logic hoisted to module level (js-cache-function-results pattern)
 * - Early return for zero count (js-early-exit)
 *
 * @see packages/css/src/components/badge.css
 * @see packages/tokens/src/components/badge.json
 */

import { forwardRef, type HTMLAttributes } from 'react';
import type { BadgeType, BadgeState, BadgeContext } from '../types';
import { cn } from '../utils/cn';

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  count: number;
  context?: BadgeContext;
  type?: BadgeType;
  state?: BadgeState;
}

// ── Badge Display Logic (hoisted pure function) ───────────
// Rule: js-cache-function-results - Pure logic at module level
function getBadgeDisplay(count: number, context: BadgeContext): string | null {
  // Rule: js-early-exit - Return early for invalid cases
  if (count <= 0) return null;

  if (context === 'inbox') {
    // Inbox context: cap at +50
    if (count >= 50) return '+50';
    return count.toString();
  }

  // Default context: cap at 99+
  if (count > 99) return '99+';
  return count.toString();
}

export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  ({ count = 0, context = 'default', type = 'neutral', state = 'default', className, ...rest }, ref) => {
    const displayValue = getBadgeDisplay(count, context);

    // Don't render if count is zero or invalid
    if (!displayValue) return null;

    const ariaLabel = `${count} ${count === 1 ? 'notification' : 'notifications'}`;

    const classes = cn('badge', `badge--${type}`, `badge--${state}`, className);

    return (
      <span
        ref={ref}
        className={classes}
        data-badge
        data-count={count}
        data-context={context}
        data-state={state}
        role="status"
        aria-label={ariaLabel}
        {...rest}
      >
        <span className="badge__text" data-badge-text>
          {displayValue}
        </span>
      </span>
    );
  }
);

Badge.displayName = 'Badge';
