// packages/components-vue/src/atoms/indicators/Tag.vue
<script setup lang="ts">
/**
 * Tag (Atom)
 *
 * A non-interactive label for categorization and metadata display.
 * Supports filled/outlined variants and semantic color states.
 *
 * Data Attributes (Animation Contract):
 * - data-tag: Root element (discovery)
 *
 * Usage:
 * <Tag variant="filled" color="success">Active</Tag>
 * <Tag variant="outlined" color="warning" size="s">Beta</Tag>
 *
 * @see packages/css/src/components/tag.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { TagVariant, TagColor, TagSize } from '../../types/tag'

interface TagProps {
  variant?: TagVariant
  color?: TagColor
  size?: TagSize
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<TagProps>(), {
  variant: 'filled',
  color: 'default',
  size: 'm'
})

const tagClasses = computed(() => [
  'tag',
  `tag--${props.variant}`,
  `tag--${props.color}`,
  `tag--${props.size}`,
  props.class
])
</script>

<template>
  <span :class="tagClasses" data-tag>
    <slot />
  </span>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/atoms/Tag.tsx
/**
 * Tag (Atom)
 *
 * Non-interactive label for categorization and metadata display.
 * Similar to Chip but without interaction states.
 *
 * Performance: Simple component, no optimization needed
 *
 * @see packages/css/src/components/tag.css
 * @see packages/tokens/src/components/tag.json
 */

import { forwardRef, type HTMLAttributes } from 'react';
import type { SizeVariant } from '../types';
import { cn } from '../utils/cn';

export interface TagProps extends HTMLAttributes<HTMLSpanElement> {
  size?: SizeVariant;
  icon?: React.ReactNode;
}

export const Tag = forwardRef<HTMLSpanElement, TagProps>(
  ({ size = 'm', icon, children, className, ...rest }, ref) => {
    const classes = cn('tag', `tag--${size}`, className);

    return (
      <span ref={ref} className={classes} data-tag data-size={size} {...rest}>
        {icon && (
          <span className="tag__icon" data-tag-icon>
            {icon}
          </span>
        )}
        <span className="tag__label" data-tag-label>
          {children}
        </span>
      </span>
    );
  }
);

Tag.displayName = 'Tag';
