// packages/components-angular/src/atoms/lists/number-item.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from '@angular/core';

/**
 * A list item for ordered numbered lists.
 *
 * @example
 * <ol>
 *   <atom-number-item [number]="1">First step</atom-number-item>
 *   <atom-number-item [number]="2">Second step</atom-number-item>
 * </ol>
 *
 * @see packages/css/src/components/lists.css
 */
@Component({
  selector: 'atom-number-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <li class="number-item" [attr.data-number]="number()">
      <ng-content />
    </li>
  `,
  styles: [`:host { display: list-item; }`],
})
export class NumberItemComponent {
  number = input.required<number>();
  customClass = input<string>('', { alias: 'class' });
}

// packages/components-vue/src/atoms/lists/NumberItem.vue
<script setup lang="ts">
/**
 * NumberItem (Atom)
 *
 * A list item for ordered numbered lists.
 * Renders as a semantic li element with a data-number attribute.
 *
 * Usage:
 * <ol>
 *   <NumberItem :number="1">First step</NumberItem>
 *   <NumberItem :number="2">Second step</NumberItem>
 * </ol>
 *
 * @see packages/css/src/components/lists.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface NumberItemProps {
  number: number
  class?: HTMLAttributes['class']
}

const props = defineProps<NumberItemProps>()

const numberClasses = computed(() => ['number-item', props.class])
</script>

<template>
  <li :class="numberClasses" :data-number="number">
    <slot />
  </li>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
