// packages/components-vue/src/atoms/lists/NumberItem.vue
<script setup lang="ts">
/**
 * NumberItem (Atom)
 *
 * A list item for ordered numbered lists.
 * Renders as a semantic li element with a data-number attribute.
 *
 * Usage:
 * <ol>
 *   <NumberItem :number="1">First step</NumberItem>
 *   <NumberItem :number="2">Second step</NumberItem>
 * </ol>
 *
 * @see packages/css/src/components/lists.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface NumberItemProps {
  number: number
  class?: HTMLAttributes['class']
}

const props = defineProps<NumberItemProps>()

const numberClasses = computed(() => ['number-item', props.class])
</script>

<template>
  <li :class="numberClasses" :data-number="number">
    <slot />
  </li>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/atoms/lists/NumberItem.tsx
/**
 * NumberItem (Atom)
 *
 * List item for ordered numbered lists. numberColor maps to --number-color CSS variable.
 * HTML matches Astro component 1:1.
 *
 * @see packages/css/src/components/lists.css
 * @see packages/components-astro/src/atoms/lists/NumberItem.astro
 */

import { forwardRef, type LiHTMLAttributes } from 'react';
import { cn } from '../../utils/cn';

export interface NumberItemProps extends LiHTMLAttributes<HTMLLIElement> {
  number: number | string;
  numberColor?: string;
}

export const NumberItem = forwardRef<HTMLLIElement, NumberItemProps>(
  ({ number, numberColor, className, style, children, ...rest }, ref) => (
    <li
      ref={ref}
      className={cn('number-item', className)}
      data-number={number}
      style={numberColor ? { '--number-color': numberColor, ...style } as React.CSSProperties : style}
      {...rest}
    >
      {children}
    </li>
  )
);

NumberItem.displayName = 'NumberItem';
