// packages/components-react/src/molecules/Card.tsx
/**
 * Card (Molecule)
 *
 * Composable card container. Use with CardHeader, CardBody, CardFooter.
 * HTML matches Astro component 1:1.
 *
 * @see packages/css/src/components/card.css
 * @see packages/components-astro/src/molecules/Card.astro
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

export interface CardProps extends HTMLAttributes<HTMLDivElement> {}

export const Card = forwardRef<HTMLDivElement, CardProps>(
  ({ className, children, ...rest }, ref) => (
    <div ref={ref} className={cn('card', className)} {...rest}>
      {children}
    </div>
  )
);

Card.displayName = 'Card';

// packages/components-vue/src/molecules/Card.vue
<script setup lang="ts">
/**
 * Card (Molecule)
 *
 * Composable card container with header, body, and footer subcomponents.
 *
 * Data Attributes (Animation Contract):
 * - data-card: Root element (discovery)
 *
 * Usage:
 * <Card>
 *   <CardHeader headline="Title" />
 *   <CardBody text="Content here" />
 *   <CardFooter><Button>Action</Button></CardFooter>
 * </Card>
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface CardProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<CardProps>()

const cardClasses = computed(() => ['card', props.class])
</script>

<template>
  <div :class="cardClasses" data-card>
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
