// packages/components-angular/src/molecules/card-body.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from '@angular/core';

/**
 * Body section of a Card with headline, subhead, text, and custom content.
 *
 * @example
 * <atom-card-body headline="Title" subhead="Subtitle" text="Body text"></atom-card-body>
 *
 * @see packages/css/src/components/card.css
 */
@Component({
  selector: 'atom-card-body',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div class="card__body" data-card-body>
      @if (headline()) {
        <span class="card__body-headline" data-card-body-headline>{{ headline() }}</span>
      }
      @if (subhead()) {
        <span class="card__body-subhead" data-card-body-subhead>{{ subhead() }}</span>
      }
      @if (text()) {
        <p class="card__body-text" data-card-body-text>{{ text() }}</p>
      }
      <ng-content />
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class CardBodyComponent {
  headline = input<string>();
  subhead = input<string>();
  text = input<string>();
  customClass = input<string>('', { alias: 'class' });
}

// packages/components-vue/src/molecules/CardBody.vue
<script setup lang="ts">
/**
 * CardBody (Molecule -- Card subcomponent)
 *
 * Body section of a Card with headline, subhead, text, and custom content.
 *
 * Data Attributes (Animation Contract):
 * - data-card-body: Root element
 * - data-card-body-headline: Headline text
 * - data-card-body-subhead: Subhead text
 * - data-card-body-text: Body text
 *
 * Usage:
 * <CardBody headline="Title" subhead="Subtitle" text="Body content here" />
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface CardBodyProps {
  headline?: string
  subhead?: string
  text?: string
  class?: HTMLAttributes['class']
}

const props = defineProps<CardBodyProps>()

const bodyClasses = computed(() => ['card__body', props.class])
</script>

<template>
  <div :class="bodyClasses" data-card-body>
    <span v-if="headline" class="card__body-headline" data-card-body-headline>
      {{ headline }}
    </span>
    <span v-if="subhead" class="card__body-subhead" data-card-body-subhead>
      {{ subhead }}
    </span>
    <p v-if="text" class="card__body-text" data-card-body-text>
      {{ text }}
    </p>
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
