// packages/components-react/src/molecules/CardFooter.tsx
/**
 * CardFooter (Molecule — Card subcomponent)
 *
 * Footer section of a Card. variant drives the CSS modifier class.
 * Children are always passed explicitly in React (no default button/tag injection).
 * HTML matches Astro component 1:1.
 *
 * @see packages/css/src/components/card.css
 * @see packages/components-astro/src/molecules/CardFooter.astro
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

export interface CardFooterProps extends HTMLAttributes<HTMLDivElement> {
  variant?: 'buttons' | 'tags';
}

export const CardFooter = forwardRef<HTMLDivElement, CardFooterProps>(
  ({ variant = 'buttons', className, children, ...rest }, ref) => (
    <div
      ref={ref}
      className={cn('card-footer', `card-footer--${variant}`, className)}
      {...rest}
    >
      {children}
    </div>
  )
);

CardFooter.displayName = 'CardFooter';

// packages/components-vue/src/molecules/CardFooter.vue
<script setup lang="ts">
/**
 * CardFooter (Molecule -- Card subcomponent)
 *
 * Footer section of a Card with buttons or tags variant.
 *
 * Data Attributes (Animation Contract):
 * - data-card-footer: Root element
 * - data-card-footer-variant: Footer variant ('buttons' | 'tags')
 *
 * Usage:
 * <CardFooter variant="buttons">
 *   <Button variant="Primary">Confirm</Button>
 *   <Button variant="Secondary">Cancel</Button>
 * </CardFooter>
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

type CardFooterVariant = 'buttons' | 'tags'

interface CardFooterProps {
  variant?: CardFooterVariant
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<CardFooterProps>(), {
  variant: 'buttons'
})

const footerClasses = computed(() => [
  'card__footer',
  `card__footer--${props.variant}`,
  props.class
])
</script>

<template>
  <div
    :class="footerClasses"
    data-card-footer
    :data-card-footer-variant="variant"
  >
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
