// packages/components-angular/src/atoms/forms/checkbox.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  effect,
  ElementRef,
  viewChild,
} from '@angular/core';

export type CheckboxSize = 's' | 'm';

/**
 * A form checkbox with label support, indeterminate state, and error handling.
 *
 * @example
 * <atom-checkbox name="agree" size="m" [checked]="true">I agree</atom-checkbox>
 *
 * @see packages/css/src/components/checkbox.css
 */
@Component({
  selector: 'atom-checkbox',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <label [class]="classes()" data-checkbox>
      <input
        #inputRef
        type="checkbox"
        [name]="name()"
        [checked]="checked()"
        [disabled]="disabled()"
        class="checkbox__input"
        (change)="changed.emit($event)"
      />
      <span class="checkbox__control"></span>
      <span class="checkbox__label">
        <ng-content />
      </span>
    </label>
  `,
  styles: [`:host { display: inline-block; }`],
})
export class CheckboxComponent {
  name = input<string>();
  size = input<CheckboxSize>('m');
  checked = input<boolean>(false);
  indeterminate = input<boolean>(false);
  disabled = input<boolean>(false);
  error = input<boolean>(false);
  customClass = input<string>('', { alias: 'class' });
  changed = output<Event>();

  private inputRef = viewChild<ElementRef<HTMLInputElement>>('inputRef');

  constructor() {
    effect(() => {
      const el = this.inputRef();
      const indet = this.indeterminate();
      if (el) {
        el.nativeElement.indeterminate = indet;
      }
    });
  }

  classes = computed(() => {
    const c = [
      'checkbox',
      `checkbox--${this.size()}`,
    ];
    if (this.error()) c.push('checkbox--error');
    if (this.disabled()) c.push('checkbox--disabled');
    return c.join(' ');
  });
}

// packages/components-vue/src/atoms/forms/Checkbox.vue
<script setup lang="ts">
/**
 * Checkbox (Atom)
 *
 * A form checkbox with label support, indeterminate state, and error handling.
 * Supports two sizes and accessible labeling via default slot.
 *
 * Data Attributes (Animation Contract):
 * - data-checkbox: Root element (discovery)
 *
 * Usage:
 * <Checkbox name="agree" size="m" v-model:checked="isChecked">I agree</Checkbox>
 * <Checkbox name="partial" :indeterminate="true" />
 *
 * @see packages/css/src/components/checkbox.css
 */

import { computed, ref, watch, onMounted, type HTMLAttributes } from 'vue'

type CheckboxSize = 's' | 'm'

interface CheckboxProps {
  name?: string
  size?: CheckboxSize
  checked?: boolean
  indeterminate?: boolean
  isDisabled?: boolean
  isError?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<CheckboxProps>(), {
  size: 'm',
  checked: false,
  indeterminate: false,
  isDisabled: false,
  isError: false
})

const emit = defineEmits<{
  'update:checked': [value: boolean]
  change: [event: Event]
}>()

const inputRef = ref<HTMLInputElement | null>(null)

// Sync indeterminate property (not available as HTML attribute)
watch(
  () => props.indeterminate,
  (val) => {
    if (inputRef.value) {
      inputRef.value.indeterminate = val
    }
  }
)

onMounted(() => {
  if (inputRef.value && props.indeterminate) {
    inputRef.value.indeterminate = true
  }
})

const wrapperClasses = computed(() => [
  'checkbox',
  `checkbox--${props.size}`,
  {
    'checkbox--error': props.isError,
    'checkbox--disabled': props.isDisabled
  },
  props.class
])

function handleChange(event: Event) {
  const target = event.target as HTMLInputElement
  emit('update:checked', target.checked)
  emit('change', event)
}
</script>

<template>
  <label :class="wrapperClasses" data-checkbox>
    <input
      ref="inputRef"
      type="checkbox"
      :name="name"
      :checked="checked"
      :disabled="isDisabled"
      class="checkbox__input"
      @change="handleChange"
    />
    <span class="checkbox__control" />
    <span v-if="$slots.default" class="checkbox__label">
      <slot />
    </span>
  </label>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
