// packages/components-angular/src/atoms/forms/radio.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

export type RadioSize = 's' | 'm';

/**
 * A form radio button with title, supportive text, and error handling.
 *
 * @example
 * <atom-radio name="color" value="red" title="Red" supportiveText="A warm color"></atom-radio>
 *
 * @see packages/css/src/components/radio.css
 */
@Component({
  selector: 'atom-radio',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <label [class]="classes()" data-radio>
      <input
        type="radio"
        [name]="name()"
        [value]="value()"
        [checked]="checked()"
        [disabled]="disabled()"
        class="radio-field__input"
        (change)="changed.emit($event)"
      />
      <span class="radio-field__control"></span>
      <span class="radio-field__content">
        @if (title()) {
          <span class="radio-field__title">{{ title() }}</span>
        }
        @if (supportiveText()) {
          <span class="radio-field__supportive-text">{{ supportiveText() }}</span>
        }
        @if (error() && errorText()) {
          <span class="radio-field__error-text">{{ errorText() }}</span>
        }
      </span>
    </label>
  `,
  styles: [`:host { display: block; }`],
})
export class RadioComponent {
  name = input<string>();
  value = input<string>();
  size = input<RadioSize>('m');
  checked = input<boolean>(false);
  disabled = input<boolean>(false);
  error = input<boolean>(false);
  title = input<string>();
  supportiveText = input<string>();
  errorText = input<string>();
  customClass = input<string>('', { alias: 'class' });
  changed = output<Event>();

  classes = computed(() => {
    const c = [
      'radio-field',
      `radio-field--${this.size()}`,
    ];
    if (this.error()) c.push('radio-field--error');
    if (this.disabled()) c.push('radio-field--disabled');
    return c.join(' ');
  });
}

// packages/components-vue/src/atoms/forms/Radio.vue
<script setup lang="ts">
/**
 * Radio (Atom)
 *
 * A form radio button with title, supportive text, and error handling.
 * Supports two sizes and accessible labeling.
 *
 * Data Attributes (Animation Contract):
 * - data-radio: Root element (discovery)
 *
 * Usage:
 * <Radio name="plan" value="free" title="Free Plan" supportive-text="Basic features" />
 * <Radio name="plan" value="pro" title="Pro Plan" :is-error="true" error-text="Required" />
 *
 * @see packages/css/src/components/radio.css
 */

import { computed, type HTMLAttributes } from 'vue'

type RadioSize = 's' | 'm'

interface RadioProps {
  name?: string
  value?: string
  size?: RadioSize
  checked?: boolean
  isDisabled?: boolean
  isError?: boolean
  title?: string
  supportiveText?: string
  errorText?: string
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<RadioProps>(), {
  size: 'm',
  checked: false,
  isDisabled: false,
  isError: false
})

const emit = defineEmits<{
  'update:checked': [value: boolean]
  change: [event: Event]
}>()

const wrapperClasses = computed(() => [
  'radio-field',
  `radio-field--${props.size}`,
  {
    'radio-field--error': props.isError,
    'radio-field--disabled': props.isDisabled
  },
  props.class
])

function handleChange(event: Event) {
  const target = event.target as HTMLInputElement
  emit('update:checked', target.checked)
  emit('change', event)
}
</script>

<template>
  <label :class="wrapperClasses" data-radio>
    <input
      type="radio"
      :name="name"
      :value="value"
      :checked="checked"
      :disabled="isDisabled"
      class="radio-field__input"
      @change="handleChange"
    />
    <span class="radio-field__control" />
    <span class="radio-field__content">
      <span v-if="title" class="radio-field__title">{{ title }}</span>
      <span v-if="supportiveText" class="radio-field__supportive-text">{{ supportiveText }}</span>
      <span v-if="isError && errorText" class="radio-field__error-text">{{ errorText }}</span>
    </span>
  </label>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
