// packages/components-angular/src/atoms/forms/search-field.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

export type SearchFieldSize = 's' | 'm' | 'l';

/**
 * Search input with clear button support.
 *
 * @example
 * <atom-search-field name="q" placeholder="Search..." [value]="query" (cleared)="onClear()"></atom-search-field>
 *
 * @see packages/css/src/components/search-field.css
 */
@Component({
  selector: 'atom-search-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    @let filled = isFilled();

    <div [class]="classes()" data-search-field>
      <span class="search-field__search-icon" aria-hidden="true"></span>
      <input
        [name]="name()"
        type="search"
        class="search-field__input"
        [placeholder]="placeholder()"
        [value]="value()"
        [disabled]="disabled()"
        role="searchbox"
        (input)="inputChanged.emit($event)"
      />
      @if (filled) {
        <button
          type="button"
          class="search-field__clear"
          aria-label="Clear search"
          (click)="cleared.emit()"
        >
          <span class="search-field__clear-icon" aria-hidden="true"></span>
        </button>
      }
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class SearchFieldComponent {
  name = input.required<string>();
  placeholder = input<string>('Search...');
  value = input<string>('');
  size = input<SearchFieldSize>('m');
  disabled = input<boolean>(false);
  customClass = input<string>('', { alias: 'class' });
  inputChanged = output<Event>();
  cleared = output<void>();

  isFilled = computed(() => {
    const v = this.value();
    return v !== undefined && v !== '';
  });

  classes = computed(() => {
    const c = [
      'search-field',
      `search-field--${this.size()}`,
    ];
    if (this.isFilled()) c.push('search-field--filled');
    return c.join(' ');
  });
}

// packages/components-vue/src/atoms/forms/SearchField.vue
<script setup lang="ts">
/**
 * SearchField (Atom)
 *
 * Search input with clear button support.
 *
 * Data Attributes (Animation Contract):
 * - data-search-field: Root element (discovery)
 *
 * Usage:
 * <SearchField name="search" v-model="query" @clear="query = ''" />
 * <SearchField name="filter" size="s" placeholder="Filter items..." />
 *
 * @see packages/css/src/components/search-field.css
 */

import { computed, type HTMLAttributes } from 'vue'

type SearchFieldSize = 's' | 'm' | 'l'

interface SearchFieldProps {
  name: string
  placeholder?: string
  modelValue?: string
  size?: SearchFieldSize
  isDisabled?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<SearchFieldProps>(), {
  placeholder: 'Search...',
  size: 'm',
  isDisabled: false
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  clear: []
}>()

const isFilled = computed(() => props.modelValue !== undefined && props.modelValue !== '')

const classes = computed(() => [
  'search-field',
  `search-field--${props.size}`,
  {
    'search-field--filled': isFilled.value
  },
  props.class
])

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.value)
}

function handleClear() {
  emit('update:modelValue', '')
  emit('clear')
}
</script>

<template>
  <div :class="classes" data-search-field>
    <span class="search-field__search-icon" aria-hidden="true" />
    <input
      :name="name"
      type="search"
      class="search-field__input"
      :placeholder="placeholder"
      :value="modelValue"
      :disabled="isDisabled"
      role="searchbox"
      @input="handleInput"
    />
    <button
      v-if="isFilled"
      type="button"
      class="search-field__clear"
      aria-label="Clear search"
      @click="handleClear"
    >
      <span class="search-field__clear-icon" aria-hidden="true" />
    </button>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
