// packages/components-angular/src/atoms/forms/text-area.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

export type TextAreaSize = 'm' | 'xl';

/**
 * Multi-line text input with label, supportive text, and character counter.
 *
 * @example
 * <atom-text-area name="bio" label="Biography" placeholder="Tell us about yourself"></atom-text-area>
 *
 * @see packages/css/src/components/textarea.css
 */
@Component({
  selector: 'atom-text-area',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    @let hasError = !!error();
    @let textareaId = 'textarea-' + name();
    @let supportiveId = textareaId + '-supportive';
    @let errorId = textareaId + '-error';

    <div [class]="classes()" data-textarea>
      @if (label()) {
        <label class="textarea__label" [attr.for]="textareaId">{{ label() }}</label>
      }
      <textarea
        [id]="textareaId"
        [name]="name()"
        class="textarea__input"
        [placeholder]="placeholder()"
        [value]="value()"
        [disabled]="disabled()"
        [attr.maxlength]="maxLength()"
        [attr.aria-invalid]="hasError || null"
        [attr.aria-describedby]="hasError ? errorId : supportiveText() ? supportiveId : null"
        (input)="inputChanged.emit($event)"
      ></textarea>
      @if (hasError) {
        <span class="textarea__error" [id]="errorId" role="alert">{{ error() }}</span>
      }
      @if (!hasError && supportiveText()) {
        <span class="textarea__supportive" [id]="supportiveId">{{ supportiveText() }}</span>
      }
      @if (showCounter() && maxLength()) {
        <span class="textarea__counter" aria-live="polite">
          {{ currentLength() }}/{{ maxLength() }}
        </span>
      }
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class TextAreaComponent {
  name = input.required<string>();
  label = input<string>();
  placeholder = input<string>('');
  value = input<string>('');
  size = input<TextAreaSize>('m');
  disabled = input<boolean>(false);
  error = input<string>();
  supportiveText = input<string>();
  maxLength = input<number>();
  showCounter = input<boolean>(false);
  customClass = input<string>('', { alias: 'class' });
  inputChanged = output<Event>();

  currentLength = computed(() => (this.value() ?? '').length);

  classes = computed(() => {
    const c = [
      'textarea',
      `textarea--${this.size()}`,
    ];
    const v = this.value();
    if (v !== undefined && v !== '') c.push('textarea--filled');
    if (this.error()) c.push('textarea--error');
    if (this.disabled()) c.push('textarea--disabled');
    return c.join(' ');
  });
}

// packages/components-vue/src/atoms/forms/TextArea.vue
<script setup lang="ts">
/**
 * TextArea (Atom)
 *
 * Multi-line text input with label, supportive text, and character counter.
 *
 * Data Attributes (Animation Contract):
 * - data-textarea: Root element (discovery)
 *
 * Usage:
 * <TextArea name="bio" label="Bio" v-model="bio" />
 * <TextArea name="description" label="Description" :max-length="500" :show-counter="true" />
 *
 * @see packages/css/src/components/textarea.css
 */

import { computed, type HTMLAttributes } from 'vue'

type TextAreaSize = 'm' | 'xl'

interface TextAreaProps {
  name: string
  label?: string
  placeholder?: string
  modelValue?: string
  size?: TextAreaSize
  isDisabled?: boolean
  error?: string
  supportiveText?: string
  maxLength?: number
  showCounter?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<TextAreaProps>(), {
  size: 'm',
  isDisabled: false,
  showCounter: false
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const isFilled = computed(() => props.modelValue !== undefined && props.modelValue !== '')
const hasError = computed(() => !!props.error)

const classes = computed(() => [
  'textarea',
  `textarea--${props.size}`,
  {
    'textarea--filled': isFilled.value,
    'textarea--error': hasError.value,
    'textarea--disabled': props.isDisabled
  },
  props.class
])

const textareaId = computed(() => `textarea-${props.name}`)
const supportiveId = computed(() => `${textareaId.value}-supportive`)
const errorId = computed(() => `${textareaId.value}-error`)
const currentLength = computed(() => typeof props.modelValue === 'string' ? props.modelValue.length : 0)

const ariaDescribedby = computed(() => {
  if (hasError.value) return errorId.value
  if (props.supportiveText) return supportiveId.value
  return undefined
})

function handleInput(event: Event) {
  const target = event.target as HTMLTextAreaElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <div :class="classes" data-textarea>
    <label v-if="label" class="textarea__label" :for="textareaId">
      {{ label }}
    </label>
    <textarea
      :id="textareaId"
      :name="name"
      class="textarea__input"
      :placeholder="placeholder"
      :value="modelValue"
      :disabled="isDisabled"
      :maxlength="maxLength"
      :aria-invalid="hasError || undefined"
      :aria-describedby="ariaDescribedby"
      @input="handleInput"
    />
    <span v-if="hasError" class="textarea__error" :id="errorId" role="alert">
      {{ error }}
    </span>
    <span v-if="!hasError && supportiveText" class="textarea__supportive" :id="supportiveId">
      {{ supportiveText }}
    </span>
    <span v-if="showCounter && maxLength" class="textarea__counter" aria-live="polite">
      {{ currentLength }}/{{ maxLength }}
    </span>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
