// packages/components-react/src/atoms/forms/TextField.tsx
/**
 * TextField (Atom)
 *
 * Single-line text input with label, supportive text, and character counter.
 * HTML output mirrors the Astro component exactly.
 *
 * @see packages/css/src/components/forms/text-field.css
 * @see packages/tokens/src/components/forms/text-field.json
 */

import { forwardRef, type InputHTMLAttributes, type ReactNode } from 'react';
import type { SizeVariant } from '../../types';
import { cn } from '../../utils/cn';

// ── Static Icons (hoisted) ────────────────────────────────
const InfoIcon = (
  <svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path
      d="M6 11C8.76142 11 11 8.76142 11 6C11 3.23858 8.76142 1 6 1C3.23858 1 1 3.23858 1 6C1 8.76142 3.23858 11 6 11Z"
      stroke="currentColor" strokeWidth="1.5"
    />
    <path
      d="M6 6V8.5M6 3.5H6.005V3.505H6V3.5Z"
      stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"
    />
  </svg>
);

const ErrorIcon = (
  <svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path
      d="M6 11C8.76142 11 11 8.76142 11 6C11 3.23858 8.76142 1 6 1C3.23858 1 1 3.23858 1 6C1 8.76142 3.23858 11 6 11Z"
      fill="currentColor"
    />
    <path d="M7.5 4.5L4.5 7.5M4.5 4.5L7.5 7.5" />
  </svg>
);

// ── TextField Props ───────────────────────────────────────
export interface TextFieldProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size'> {
  name: string;
  label?: string;
  size?: SizeVariant;
  error?: boolean;
  showSupportive?: boolean;
  supportiveText?: string;
  maxLength?: number;
  showCounter?: boolean;
  id?: string;
  leading?: ReactNode;
  trailing?: ReactNode;
}

// ── TextField Component ───────────────────────────────────
export const TextField = forwardRef<HTMLInputElement, TextFieldProps>(
  (props, ref) => {
    const {
      name,
      type = 'text',
      label,
      placeholder,
      value,
      size = 'm',
      disabled = false,
      error = false,
      showSupportive = true,
      supportiveText = error ? 'Supportive text negative' : 'Supportive text',
      maxLength = 200,
      showCounter = false,
      id,
      className,
      onChange,
      leading,
      trailing,
      ...rest
    } = props;

    const inputId = id || `text-field-${name}`;
    const isFilled = value !== undefined && value !== '';
    const charCount = typeof value === 'string' ? value.length : 0;

    return (
      <div
        className={cn(
          'text-field',
          `text-field--${size}`,
          isFilled && 'text-field--filled',
          error && 'text-field--error',
          disabled && 'text-field--disabled',
          className
        )}
        data-text-field
        data-max-length={maxLength}
      >
        {/* Label */}
        {label && (
          <label className="text-field__label" htmlFor={inputId}>
            {label}
          </label>
        )}

        {/* Field container */}
        <div className="text-field__field">
          {leading && <div className="text-field__leading">{leading}</div>}

          <input
            ref={ref}
            className="text-field__input"
            type={type}
            id={inputId}
            name={name}
            placeholder={placeholder}
            value={value}
            disabled={disabled}
            maxLength={maxLength}
            onChange={onChange}
            {...rest}
          />

          {trailing && <div className="text-field__trailing">{trailing}</div>}
        </div>

        {/* Bottom: supportive text + counter */}
        {(showSupportive || showCounter) && (
          <div className="text-field__bottom">
            {showSupportive && (
              <div className="text-field__supportive">
                <div className="text-field__supportive-icon" aria-hidden="true">
                  {error ? ErrorIcon : InfoIcon}
                </div>
                <span className="text-field__supportive-text">{supportiveText}</span>
              </div>
            )}
            {showCounter && (
              <div className="text-field__counter" data-counter data-char-count={charCount}>
                <span data-current>{charCount}</span>/<span data-max>{maxLength}</span>
              </div>
            )}
          </div>
        )}
      </div>
    );
  }
);

TextField.displayName = 'TextField';

// packages/components-vue/src/atoms/forms/TextField.vue
<script setup lang="ts">
/**
 * TextField (Atom)
 *
 * Single-line text input with label, supportive text, and character counter.
 *
 * Data Attributes (Animation Contract):
 * - data-text-field: Root element (discovery)
 *
 * Usage:
 * <TextField name="email" label="Email" v-model="email" />
 * <TextField name="username" label="Username" error="Already taken" />
 *
 * @see packages/css/src/components/text-field.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { Size } from '../../types'

interface TextFieldProps {
  name: string
  label?: string
  placeholder?: string
  modelValue?: string
  size?: Size
  isDisabled?: boolean
  error?: string
  supportiveText?: string
  maxLength?: number
  showCounter?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<TextFieldProps>(), {
  size: 'm',
  isDisabled: false,
  showCounter: false
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const isFilled = computed(() => props.modelValue !== undefined && props.modelValue !== '')
const hasError = computed(() => !!props.error)

const classes = computed(() => [
  'text-field',
  `text-field--${props.size}`,
  {
    'text-field--filled': isFilled.value,
    'text-field--error': hasError.value,
    'text-field--disabled': props.isDisabled
  },
  props.class
])

const inputId = computed(() => `text-field-${props.name}`)
const supportiveId = computed(() => `${inputId.value}-supportive`)
const errorId = computed(() => `${inputId.value}-error`)
const currentLength = computed(() => typeof props.modelValue === 'string' ? props.modelValue.length : 0)

const ariaDescribedby = computed(() => {
  if (hasError.value) return errorId.value
  if (props.supportiveText) return supportiveId.value
  return undefined
})

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <div :class="classes" data-text-field>
    <label v-if="label" class="text-field__label" :for="inputId">
      {{ label }}
    </label>
    <input
      :id="inputId"
      :name="name"
      type="text"
      class="text-field__input"
      :placeholder="placeholder"
      :value="modelValue"
      :disabled="isDisabled"
      :maxlength="maxLength"
      :aria-invalid="hasError || undefined"
      :aria-describedby="ariaDescribedby"
      @input="handleInput"
    />
    <span v-if="hasError" class="text-field__error" :id="errorId" role="alert">
      {{ error }}
    </span>
    <span v-if="!hasError && supportiveText" class="text-field__supportive" :id="supportiveId">
      {{ supportiveText }}
    </span>
    <span v-if="showCounter && maxLength" class="text-field__counter" aria-live="polite">
      {{ currentLength }}/{{ maxLength }}
    </span>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
