// packages/components-react/src/atoms/buttons/LinkButton.tsx
/**
 * LinkButton (Atom)
 *
 * Text link styled as a button with optional icon support.
 * Single visual style (no variant), two sizes.
 *
 * Performance optimizations:
 * - Static icons hoisted to module level (rendering-hoist-jsx)
 * - forwardRef for ref forwarding
 * - No inline component definitions (rerender-no-inline-components)
 *
 * @see packages/css/src/components/link-button.css
 * @see packages/tokens/src/components/link-button.json
 */

import { forwardRef, type AnchorHTMLAttributes, type ReactNode } from 'react';
import { cn } from '../../utils/cn';

// ── Static Icons (hoisted) ────────────────────────────────
const SpinnerIcon = (
  <span className="link-button__spinner" data-link-button-spinner aria-hidden="true" />
);

// ── LinkButton Size ───────────────────────────────────────
type LinkButtonSize = 's' | 'l';

// ── LinkButton Props ──────────────────────────────────────
export interface LinkButtonProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  size?: LinkButtonSize;
  disabled?: boolean;
  loading?: boolean;
  href?: string;
  iconLeft?: ReactNode;
  iconRight?: ReactNode;
}

// ── LinkButton Component ──────────────────────────────────
export const LinkButton = forwardRef<HTMLAnchorElement, LinkButtonProps>(
  (props, ref) => {
    const {
      size = 'l',
      disabled = false,
      loading = false,
      href,
      iconLeft,
      iconRight,
      className,
      children,
      ...rest
    } = props;

    const isDisabled = disabled || loading;

    const classes = cn(
      'link-button',
      `link-button--${size}`,
      isDisabled && 'link-button--disabled',
      loading && 'link-button--loading',
      className
    );

    return (
      <a
        ref={ref}
        href={href}
        className={classes}
        data-link-button
        tabIndex={isDisabled ? -1 : 0}
        {...(isDisabled && { 'aria-disabled': true })}
        {...(loading && { 'aria-busy': true })}
        {...rest}
      >
        {loading ? (
          <span className="link-button__loading-content">
            <span className="link-button__loading-text" data-shimmer>
              Loading
            </span>
            {SpinnerIcon}
          </span>
        ) : (
          <span className="link-button__label">
            {iconLeft && <span className="link-button__icon">{iconLeft}</span>}
            {children}
            {iconRight && <span className="link-button__icon">{iconRight}</span>}
          </span>
        )}
      </a>
    );
  }
);

LinkButton.displayName = 'LinkButton';

// packages/components-vue/src/atoms/buttons/LinkButton.vue
<script setup lang="ts">
/**
 * LinkButton (Atom)
 *
 * Text link styled as a button with optional icon support.
 * Single visual style (no variant), two sizes.
 *
 * Data Attributes (Animation Contract):
 * - data-link-button: Root element (discovery)
 * - data-shimmer: On loading text (shimmer animation)
 * - data-link-button-spinner: Loading spinner
 *
 * Usage:
 * <LinkButton size="l" href="/about">Learn more</LinkButton>
 * <LinkButton size="s" :is-loading="true">Loading...</LinkButton>
 *
 * @see packages/css/src/components/link-button.css
 */

import { computed, type HTMLAttributes } from 'vue'

type LinkButtonSize = 's' | 'l'

interface LinkButtonProps {
  size?: LinkButtonSize
  href?: string
  isDisabled?: boolean
  isLoading?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<LinkButtonProps>(), {
  size: 'l',
  isDisabled: false,
  isLoading: false
})

const isDisabled = computed(() => props.isDisabled || props.isLoading)

const linkButtonClasses = computed(() => [
  'link-button',
  `link-button--${props.size}`,
  {
    'link-button--disabled': isDisabled.value,
    'link-button--loading': props.isLoading
  },
  props.class
])
</script>

<template>
  <a
    :href="href"
    :class="linkButtonClasses"
    data-link-button
    :tabindex="isDisabled ? -1 : 0"
    :aria-disabled="isDisabled ? 'true' : undefined"
    :aria-busy="isLoading ? 'true' : undefined"
  >
    <span v-if="isLoading" class="link-button__loading-content">
      <span class="link-button__loading-text" data-shimmer>Loading</span>
      <span class="link-button__spinner" data-link-button-spinner aria-hidden="true" />
    </span>

    <span v-else class="link-button__label">
      <span v-if="$slots.iconLeft" class="link-button__icon">
        <slot name="iconLeft" />
      </span>
      <slot />
      <span v-if="$slots.iconRight" class="link-button__icon">
        <slot name="iconRight" />
      </span>
    </span>
  </a>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
