// packages/components-vue/src/atoms/forms/TextField.vue
<script setup lang="ts">
/**
 * TextField (Atom)
 *
 * Single-line text input with label, supportive text, and character counter.
 *
 * Data Attributes (Animation Contract):
 * - data-text-field: Root element (discovery)
 *
 * Usage:
 * <TextField name="email" label="Email" v-model="email" />
 * <TextField name="username" label="Username" error="Already taken" />
 *
 * @see packages/css/src/components/text-field.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { Size } from '../../types'

interface TextFieldProps {
  name: string
  label?: string
  placeholder?: string
  modelValue?: string
  size?: Size
  isDisabled?: boolean
  error?: string
  supportiveText?: string
  maxLength?: number
  showCounter?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<TextFieldProps>(), {
  size: 'm',
  isDisabled: false,
  showCounter: false
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const isFilled = computed(() => props.modelValue !== undefined && props.modelValue !== '')
const hasError = computed(() => !!props.error)

const classes = computed(() => [
  'text-field',
  `text-field--${props.size}`,
  {
    'text-field--filled': isFilled.value,
    'text-field--error': hasError.value,
    'text-field--disabled': props.isDisabled
  },
  props.class
])

const inputId = computed(() => `text-field-${props.name}`)
const supportiveId = computed(() => `${inputId.value}-supportive`)
const errorId = computed(() => `${inputId.value}-error`)
const currentLength = computed(() => typeof props.modelValue === 'string' ? props.modelValue.length : 0)

const ariaDescribedby = computed(() => {
  if (hasError.value) return errorId.value
  if (props.supportiveText) return supportiveId.value
  return undefined
})

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <div :class="classes" data-text-field>
    <label v-if="label" class="text-field__label" :for="inputId">
      {{ label }}
    </label>
    <input
      :id="inputId"
      :name="name"
      type="text"
      class="text-field__input"
      :placeholder="placeholder"
      :value="modelValue"
      :disabled="isDisabled"
      :maxlength="maxLength"
      :aria-invalid="hasError || undefined"
      :aria-describedby="ariaDescribedby"
      @input="handleInput"
    />
    <span v-if="hasError" class="text-field__error" :id="errorId" role="alert">
      {{ error }}
    </span>
    <span v-if="!hasError && supportiveText" class="text-field__supportive" :id="supportiveId">
      {{ supportiveText }}
    </span>
    <span v-if="showCounter && maxLength" class="text-field__counter" aria-live="polite">
      {{ currentLength }}/{{ maxLength }}
    </span>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/forms/text-field.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

/**
 * Single-line text input with label, supportive text, and character counter.
 *
 * @example
 * <atom-text-field name="email" label="Email" placeholder="you@example.com"></atom-text-field>
 *
 * @see packages/css/src/components/text-field.css
 */
@Component({
  selector: 'atom-text-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    @let hasError = !!error();
    @let inputId = 'text-field-' + name();
    @let supportiveId = inputId + '-supportive';
    @let errorId = inputId + '-error';

    <div [class]="classes()" data-text-field>
      @if (label()) {
        <label class="text-field__label" [attr.for]="inputId">{{ label() }}</label>
      }
      <input
        [id]="inputId"
        [name]="name()"
        type="text"
        class="text-field__input"
        [placeholder]="placeholder()"
        [value]="value()"
        [disabled]="disabled()"
        [attr.maxlength]="maxLength()"
        [attr.aria-invalid]="hasError || null"
        [attr.aria-describedby]="hasError ? errorId : supportiveText() ? supportiveId : null"
        (input)="inputChanged.emit($event)"
      />
      @if (hasError) {
        <span class="text-field__error" [id]="errorId" role="alert">{{ error() }}</span>
      }
      @if (!hasError && supportiveText()) {
        <span class="text-field__supportive" [id]="supportiveId">{{ supportiveText() }}</span>
      }
      @if (showCounter() && maxLength()) {
        <span class="text-field__counter" aria-live="polite">
          {{ currentLength() }}/{{ maxLength() }}
        </span>
      }
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class TextFieldComponent {
  name = input.required<string>();
  label = input<string>();
  placeholder = input<string>('');
  value = input<string>('');
  size = input<'xs' | 's' | 'm' | 'l' | 'xl'>('m');
  disabled = input<boolean>(false);
  error = input<string>();
  supportiveText = input<string>();
  maxLength = input<number>();
  showCounter = input<boolean>(false);
  customClass = input<string>('', { alias: 'class' });
  inputChanged = output<Event>();

  currentLength = computed(() => (this.value() ?? '').length);

  classes = computed(() => {
    const c = [
      'text-field',
      `text-field--${this.size()}`,
    ];
    const v = this.value();
    if (v !== undefined && v !== '') c.push('text-field--filled');
    if (this.error()) c.push('text-field--error');
    if (this.disabled()) c.push('text-field--disabled');
    return c.join(' ');
  });
}
