// packages/components-react/src/layout/Stack.tsx
/**
 * Stack (Layout)
 *
 * Vertical stack layout with configurable gap and alignment.
 * Supports polymorphic rendering via the `as` prop.
 *
 * @see packages/css/src/layout/stack.css
 */

import { forwardRef, type HTMLAttributes } from 'react';
import type { GapSize, Alignment } from '../types';
import { cn } from '../utils/cn';

// ── Types ────────────────────────────────────────────────
export interface StackProps extends HTMLAttributes<HTMLElement> {
  gap?: GapSize;
  align?: Alignment;
  as?: 'div' | 'section' | 'article';
}

// ── Stack Component ──────────────────────────────────────
export const Stack = forwardRef<HTMLElement, StackProps>(
  ({ gap = 'm', align, as: Tag = 'div', className, children, ...rest }, ref) => {
    const classes = cn(
      'stack',
      `stack--gap-${gap}`,
      align && `stack--align-${align}`,
      className
    );

    return (
      <Tag ref={ref as React.Ref<HTMLDivElement>} className={classes} data-stack data-gap={gap} {...rest}>
        {children}
      </Tag>
    );
  }
);

Stack.displayName = 'Stack';

// packages/components-vue/src/layout/Stack.vue
<script setup lang="ts">
/**
 * Stack (Layout)
 *
 * Vertical stack layout with configurable gap and alignment.
 * Supports polymorphic rendering via the `as` prop.
 *
 * Data Attributes (Animation Contract):
 * - data-stack: Root element (discovery)
 * - data-gap: Gap size
 *
 * Usage:
 * <Stack gap="l" align="center">
 *   <Heading>Title</Heading>
 *   <Text>Content</Text>
 * </Stack>
 *
 * @see packages/css/src/layout/stack.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { GapSize, LayoutAlignment } from '../types/layout'

interface StackProps {
  gap?: GapSize
  align?: LayoutAlignment
  as?: 'div' | 'section' | 'article'
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<StackProps>(), {
  gap: 'm',
  as: 'div'
})

const stackClasses = computed(() => [
  'stack',
  `stack--gap-${props.gap}`,
  props.align && `stack--align-${props.align}`,
  props.class
])
</script>

<template>
  <component :is="as" :class="stackClasses" data-stack :data-gap="gap">
    <slot />
  </component>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
