// packages/components-angular/src/layout/stack.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type GapSize = 'xs' | 's' | 'm' | 'l' | 'xl';
export type Alignment = 'start' | 'center' | 'end' | 'stretch';

/**
 * Vertical stack layout with configurable gap and alignment.
 *
 * @example
 * <atom-stack gap="m" align="center">
 *   <p>Item 1</p>
 *   <p>Item 2</p>
 * </atom-stack>
 *
 * @see packages/css/src/layout/stack.css
 */
@Component({
  selector: 'atom-stack',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div [class]="classes()" data-stack [attr.data-gap]="gap()">
      <ng-content />
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class StackComponent {
  gap = input<GapSize>('m');
  align = input<Alignment>();
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    const c = ['stack', `stack--gap-${this.gap()}`];
    const a = this.align();
    if (a) c.push(`stack--align-${a}`);
    return c.join(' ');
  });
}

// packages/components-vue/src/layout/Stack.vue
<script setup lang="ts">
/**
 * Stack (Layout)
 *
 * Vertical stack layout with configurable gap and alignment.
 * Supports polymorphic rendering via the `as` prop.
 *
 * Data Attributes (Animation Contract):
 * - data-stack: Root element (discovery)
 * - data-gap: Gap size
 *
 * Usage:
 * <Stack gap="l" align="center">
 *   <Heading>Title</Heading>
 *   <Text>Content</Text>
 * </Stack>
 *
 * @see packages/css/src/layout/stack.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { GapSize, LayoutAlignment } from '../types/layout'

interface StackProps {
  gap?: GapSize
  align?: LayoutAlignment
  as?: 'div' | 'section' | 'article'
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<StackProps>(), {
  gap: 'm',
  as: 'div'
})

const stackClasses = computed(() => [
  'stack',
  `stack--gap-${props.gap}`,
  props.align && `stack--align-${props.align}`,
  props.class
])
</script>

<template>
  <component :is="as" :class="stackClasses" data-stack :data-gap="gap">
    <slot />
  </component>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
