// packages/components-react/src/layout/Container.tsx
/**
 * Container (Layout)
 *
 * Constrains content width with responsive max-width variants.
 *
 * @see packages/css/src/layout/container.css
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

// ── Types ────────────────────────────────────────────────
export interface ContainerProps extends HTMLAttributes<HTMLDivElement> {
  size?: 'default' | 'medium' | 'small';
}

// ── Container Component ──────────────────────────────────
export const Container = forwardRef<HTMLDivElement, ContainerProps>(
  ({ size = 'default', className, children, ...rest }, ref) => {
    const classes = cn(
      'container',
      size !== 'default' && `container--${size}`,
      className
    );

    return (
      <div ref={ref} className={classes} data-container data-size={size} {...rest}>
        {children}
      </div>
    );
  }
);

Container.displayName = 'Container';

// packages/components-angular/src/layout/container.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type ContainerSize = 'default' | 'medium' | 'small';

/**
 * Constrains content width with responsive max-width variants.
 *
 * @example
 * <atom-container size="default">
 *   <p>Centered content</p>
 * </atom-container>
 *
 * @see packages/css/src/layout/container.css
 */
@Component({
  selector: 'atom-container',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div [class]="classes()" data-container [attr.data-size]="size()">
      <ng-content />
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class ContainerComponent {
  size = input<ContainerSize>('default');
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    const c = ['container'];
    const s = this.size();
    if (s !== 'default') c.push(`container--${s}`);
    return c.join(' ');
  });
}
