// packages/components-vue/src/layout/Center.vue
<script setup lang="ts">
/**
 * Center (Layout)
 *
 * Centers its children both horizontally and vertically.
 *
 * Data Attributes (Animation Contract):
 * - data-center: Root element (discovery)
 *
 * Usage:
 * <Center>
 *   <Spinner size="l" />
 * </Center>
 *
 * @see packages/css/src/layout/center.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface CenterProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<CenterProps>()

const centerClasses = computed(() => ['center', props.class])
</script>

<template>
  <div :class="centerClasses" data-center>
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/layout/Center.tsx
/**
 * Center (Layout)
 *
 * Centers its children both horizontally and vertically.
 *
 * @see packages/css/src/layout/center.css
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

// ── Types ────────────────────────────────────────────────
export interface CenterProps extends HTMLAttributes<HTMLDivElement> {}

// ── Center Component ─────────────────────────────────────
export const Center = forwardRef<HTMLDivElement, CenterProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = cn('center', className);

    return (
      <div ref={ref} className={classes} data-center {...rest}>
        {children}
      </div>
    );
  }
);

Center.displayName = 'Center';
