// packages/components-vue/src/layout/Container.vue
<script setup lang="ts">
/**
 * Container (Layout)
 *
 * Constrains content width with responsive max-width variants.
 *
 * Data Attributes (Animation Contract):
 * - data-container: Root element (discovery)
 * - data-size: Container size variant
 *
 * Usage:
 * <Container>Default width content</Container>
 * <Container size="small">Narrow content</Container>
 *
 * @see packages/css/src/layout/container.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { ContainerSize } from '../types/layout'

interface ContainerProps {
  size?: ContainerSize
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<ContainerProps>(), {
  size: 'default'
})

const containerClasses = computed(() => [
  'container',
  props.size !== 'default' && `container--${props.size}`,
  props.class
])
</script>

<template>
  <div :class="containerClasses" data-container :data-size="size">
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/layout/Container.tsx
/**
 * Container (Layout)
 *
 * Constrains content width with responsive max-width variants.
 *
 * @see packages/css/src/layout/container.css
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

// ── Types ────────────────────────────────────────────────
export interface ContainerProps extends HTMLAttributes<HTMLDivElement> {
  size?: 'default' | 'medium' | 'small';
}

// ── Container Component ──────────────────────────────────
export const Container = forwardRef<HTMLDivElement, ContainerProps>(
  ({ size = 'default', className, children, ...rest }, ref) => {
    const classes = cn(
      'container',
      size !== 'default' && `container--${size}`,
      className
    );

    return (
      <div ref={ref} className={classes} data-container data-size={size} {...rest}>
        {children}
      </div>
    );
  }
);

Container.displayName = 'Container';
