// packages/components-vue/src/layout/Inline.vue
<script setup lang="ts">
/**
 * Inline (Layout)
 *
 * Horizontal inline layout with configurable gap, alignment, and wrapping.
 *
 * Data Attributes (Animation Contract):
 * - data-inline: Root element (discovery)
 * - data-gap: Gap size
 *
 * Usage:
 * <Inline gap="s" align="center">
 *   <Button>One</Button>
 *   <Button>Two</Button>
 * </Inline>
 *
 * @see packages/css/src/layout/inline.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { GapSize, LayoutAlignment } from '../types/layout'

interface InlineProps {
  gap?: GapSize
  align?: LayoutAlignment
  isWrap?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<InlineProps>(), {
  gap: 'm',
  isWrap: false
})

const inlineClasses = computed(() => [
  'inline',
  `inline--gap-${props.gap}`,
  props.align && `inline--align-${props.align}`,
  {
    'inline--wrap': props.isWrap
  },
  props.class
])
</script>

<template>
  <div :class="inlineClasses" data-inline :data-gap="gap">
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/layout/Inline.tsx
/**
 * Inline (Layout)
 *
 * Horizontal inline layout with configurable gap, alignment, and wrapping.
 *
 * @see packages/css/src/layout/inline.css
 */

import { forwardRef, type HTMLAttributes } from 'react';
import type { GapSize, Alignment } from '../types';
import { cn } from '../utils/cn';

// ── Types ────────────────────────────────────────────────
export interface InlineProps extends HTMLAttributes<HTMLDivElement> {
  gap?: GapSize;
  align?: Alignment;
  wrap?: boolean;
}

// ── Inline Component ─────────────────────────────────────
export const Inline = forwardRef<HTMLDivElement, InlineProps>(
  ({ gap = 'm', align, wrap = false, className, children, ...rest }, ref) => {
    const classes = cn(
      'inline',
      `inline--gap-${gap}`,
      align && `inline--align-${align}`,
      wrap && 'inline--wrap',
      className
    );

    return (
      <div ref={ref} className={classes} data-inline data-gap={gap} {...rest}>
        {children}
      </div>
    );
  }
);

Inline.displayName = 'Inline';
