// packages/components-vue/src/layout/Section.vue
<script setup lang="ts">
/**
 * Section (Layout)
 *
 * Semantic section wrapper for page content blocks.
 *
 * Data Attributes (Animation Contract):
 * - data-section: Root element (discovery)
 *
 * Usage:
 * <Section>
 *   <Heading>Section Title</Heading>
 *   <Text>Section content here</Text>
 * </Section>
 *
 * @see packages/css/src/layout/section.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface SectionProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<SectionProps>()

const sectionClasses = computed(() => ['section', props.class])
</script>

<template>
  <section :class="sectionClasses" data-section>
    <slot />
  </section>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/layout/Section.tsx
/**
 * Section (Layout)
 *
 * Semantic section wrapper for page content blocks.
 *
 * @see packages/css/src/layout/section.css
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

// ── Types ────────────────────────────────────────────────
export interface SectionProps extends HTMLAttributes<HTMLElement> {}

// ── Section Component ────────────────────────────────────
export const Section = forwardRef<HTMLElement, SectionProps>(
  ({ className, children, ...rest }, ref) => {
    const classes = cn('section', className);

    return (
      <section ref={ref} className={classes} data-section {...rest}>
        {children}
      </section>
    );
  }
);

Section.displayName = 'Section';
