// packages/components-vue/src/molecules/CardFooter.vue
<script setup lang="ts">
/**
 * CardFooter (Molecule -- Card subcomponent)
 *
 * Footer section of a Card with buttons or tags variant.
 *
 * Data Attributes (Animation Contract):
 * - data-card-footer: Root element
 * - data-card-footer-variant: Footer variant ('buttons' | 'tags')
 *
 * Usage:
 * <CardFooter variant="buttons">
 *   <Button variant="Primary">Confirm</Button>
 *   <Button variant="Secondary">Cancel</Button>
 * </CardFooter>
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

type CardFooterVariant = 'buttons' | 'tags'

interface CardFooterProps {
  variant?: CardFooterVariant
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<CardFooterProps>(), {
  variant: 'buttons'
})

const footerClasses = computed(() => [
  'card__footer',
  `card__footer--${props.variant}`,
  props.class
])
</script>

<template>
  <div
    :class="footerClasses"
    data-card-footer
    :data-card-footer-variant="variant"
  >
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/molecules/card-footer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type CardFooterVariant = 'buttons' | 'tags';

/**
 * Footer section of a Card with buttons or tags variant.
 *
 * @example
 * <atom-card-footer variant="buttons">
 *   <atom-button variant="Primary">Save</atom-button>
 *   <atom-button variant="Secondary">Cancel</atom-button>
 * </atom-card-footer>
 *
 * @see packages/css/src/components/card.css
 */
@Component({
  selector: 'atom-card-footer',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div
      [class]="classes()"
      data-card-footer
      [attr.data-card-footer-variant]="variant()"
    >
      <ng-content />
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class CardFooterComponent {
  variant = input<CardFooterVariant>('buttons');
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    return ['card__footer', `card__footer--${this.variant()}`].join(' ');
  });
}
