// packages/components-vue/src/molecules/Card.vue
<script setup lang="ts">
/**
 * Card (Molecule)
 *
 * Composable card container with header, body, and footer subcomponents.
 *
 * Data Attributes (Animation Contract):
 * - data-card: Root element (discovery)
 *
 * Usage:
 * <Card>
 *   <CardHeader headline="Title" />
 *   <CardBody text="Content here" />
 *   <CardFooter><Button>Action</Button></CardFooter>
 * </Card>
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface CardProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<CardProps>()

const cardClasses = computed(() => ['card', props.class])
</script>

<template>
  <div :class="cardClasses" data-card>
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/molecules/card.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from '@angular/core';

/**
 * Composable card container with header, body, and footer subcomponents.
 *
 * @example
 * <atom-card>
 *   <atom-card-header headline="Title"></atom-card-header>
 *   <atom-card-body text="Some content"></atom-card-body>
 *   <atom-card-footer>
 *     <atom-button variant="Primary">Action</atom-button>
 *   </atom-card-footer>
 * </atom-card>
 *
 * @see packages/css/src/components/card.css
 */
@Component({
  selector: 'atom-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div class="card" data-card>
      <ng-content />
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class CardComponent {
  customClass = input<string>('', { alias: 'class' });
}
