// packages/components-vue/src/atoms/layout/Divider.vue
<script setup lang="ts">
/**
 * Divider (Atom)
 *
 * A visual separator for horizontal or vertical content division.
 * Renders as an hr element with semantic meaning.
 *
 * Usage:
 * <Divider />
 * <Divider orientation="vertical" />
 *
 * @see packages/css/src/components/divider.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { DividerOrientation } from '../../types/layout'

interface DividerProps {
  orientation?: DividerOrientation
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: 'horizontal'
})

const dividerClasses = computed(() => [
  'divider',
  `divider--${props.orientation}`,
  props.class
])
</script>

<template>
  <hr :class="dividerClasses" :aria-orientation="orientation" />
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/layout/divider.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type DividerOrientation = 'horizontal' | 'vertical';

/**
 * A visual separator for horizontal or vertical content division.
 *
 * @example
 * <atom-divider orientation="horizontal"></atom-divider>
 *
 * @see packages/css/src/components/divider.css
 */
@Component({
  selector: 'atom-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <hr
      [class]="classes()"
      [attr.aria-orientation]="orientation()"
    />
  `,
  styles: [`:host { display: block; }`],
})
export class DividerComponent {
  orientation = input<DividerOrientation>('horizontal');
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    return ['divider', `divider--${this.orientation()}`].join(' ');
  });
}
