// packages/components-react/src/atoms/layout/Divider.tsx
/**
 * Divider (Atom)
 *
 * Horizontal rule separator. opacity prop maps to --divider-opacity CSS variable.
 * HTML matches Astro component 1:1.
 *
 * @see packages/css/src/components/divider.css
 * @see packages/components-astro/src/atoms/layout/Divider.astro
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../../utils/cn';

export interface DividerProps extends HTMLAttributes<HTMLHRElement> {
  opacity?: number;
}

export const Divider = forwardRef<HTMLHRElement, DividerProps>(
  ({ opacity, className, style, ...rest }, ref) => (
    <hr
      ref={ref}
      className={cn('divider', className)}
      data-divider
      aria-hidden="true"
      style={opacity !== undefined ? { '--divider-opacity': opacity, ...style } as React.CSSProperties : style}
      {...rest}
    />
  )
);

Divider.displayName = 'Divider';

// packages/components-vue/src/atoms/layout/Divider.vue
<script setup lang="ts">
/**
 * Divider (Atom)
 *
 * A visual separator for horizontal or vertical content division.
 * Renders as an hr element with semantic meaning.
 *
 * Usage:
 * <Divider />
 * <Divider orientation="vertical" />
 *
 * @see packages/css/src/components/divider.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { DividerOrientation } from '../../types/layout'

interface DividerProps {
  orientation?: DividerOrientation
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: 'horizontal'
})

const dividerClasses = computed(() => [
  'divider',
  `divider--${props.orientation}`,
  props.class
])
</script>

<template>
  <hr :class="dividerClasses" :aria-orientation="orientation" />
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
