// packages/components-vue/src/atoms/navigation/Pagination.vue
<script setup lang="ts">
/**
 * Pagination (Atom)
 *
 * Table pagination with page size selector and navigation controls.
 *
 * Data Attributes (Animation Contract):
 * - data-pagination: Root element (discovery)
 *
 * Usage:
 * <Pagination :current-page="1" :total-pages="10" @page-change="goTo" />
 * <Pagination :current-page="page" :total-pages="50" :page-size="25" @page-size-change="resize" />
 *
 * @see packages/css/src/components/pagination.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface PaginationProps {
  currentPage: number
  totalPages: number
  pageSize?: number
  pageSizeOptions?: number[]
  isLoading?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<PaginationProps>(), {
  pageSize: 10,
  pageSizeOptions: () => [10, 25, 50, 100],
  isLoading: false
})

const emit = defineEmits<{
  pageChange: [page: number]
  pageSizeChange: [size: number]
}>()

const isFirstPage = computed(() => props.currentPage <= 1)
const isLastPage = computed(() => props.currentPage >= props.totalPages)

const paginationClasses = computed(() => [
  'pagination',
  {
    'pagination--loading': props.isLoading
  },
  props.class
])

function handlePageSizeChange(event: Event) {
  const target = event.target as HTMLSelectElement
  emit('pageSizeChange', Number(target.value))
}
</script>

<template>
  <nav
    :class="paginationClasses"
    data-pagination
    aria-label="Pagination"
    :aria-busy="isLoading ? 'true' : undefined"
  >
    <div v-if="pageSizeOptions.length > 0" class="pagination__page-size">
      <label class="pagination__page-size-label" for="pagination-page-size">
        Rows per page
      </label>
      <select
        id="pagination-page-size"
        class="pagination__page-size-select"
        :value="pageSize"
        :disabled="isLoading"
        @change="handlePageSizeChange"
      >
        <option v-for="option in pageSizeOptions" :key="option" :value="option">
          {{ option }}
        </option>
      </select>
    </div>
    <span class="pagination__info" aria-live="polite">
      Page {{ currentPage }} of {{ totalPages }}
    </span>
    <div class="pagination__controls">
      <button
        type="button"
        class="pagination__button pagination__button--prev"
        :disabled="isFirstPage || isLoading"
        aria-label="Previous page"
        @click="emit('pageChange', currentPage - 1)"
      >
        <span class="pagination__icon pagination__icon--prev" aria-hidden="true" />
      </button>
      <button
        type="button"
        class="pagination__button pagination__button--next"
        :disabled="isLastPage || isLoading"
        aria-label="Next page"
        @click="emit('pageChange', currentPage + 1)"
      >
        <span class="pagination__icon pagination__icon--next" aria-hidden="true" />
      </button>
    </div>
  </nav>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/navigation/pagination.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

/**
 * Table pagination with page size selector and navigation controls.
 *
 * @example
 * <atom-pagination
 *   [currentPage]="1"
 *   [totalPages]="10"
 *   [pageSize]="25"
 *   (pageChanged)="onPage($event)"
 *   (pageSizeChanged)="onPageSize($event)"
 * ></atom-pagination>
 *
 * @see packages/css/src/components/pagination.css
 */
@Component({
  selector: 'atom-pagination',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    @let first = isFirstPage();
    @let last = isLastPage();
    @let isLoading = loading();

    <nav
      [class]="classes()"
      data-pagination
      aria-label="Pagination"
      [attr.aria-busy]="isLoading ? 'true' : null"
    >
      @if (pageSizeOptions().length > 0) {
        <div class="pagination__page-size">
          <label class="pagination__page-size-label" for="pagination-page-size">
            Rows per page
          </label>
          <select
            id="pagination-page-size"
            class="pagination__page-size-select"
            [value]="pageSize()"
            [disabled]="isLoading"
            (change)="onPageSizeSelect($event)"
          >
            @for (option of pageSizeOptions(); track option) {
              <option [value]="option">{{ option }}</option>
            }
          </select>
        </div>
      }
      <span class="pagination__info" aria-live="polite">
        Page {{ currentPage() }} of {{ totalPages() }}
      </span>
      <div class="pagination__controls">
        <button
          type="button"
          class="pagination__button pagination__button--prev"
          [disabled]="first || isLoading"
          aria-label="Previous page"
          (click)="pageChanged.emit(currentPage() - 1)"
        >
          <span class="pagination__icon pagination__icon--prev" aria-hidden="true"></span>
        </button>
        <button
          type="button"
          class="pagination__button pagination__button--next"
          [disabled]="last || isLoading"
          aria-label="Next page"
          (click)="pageChanged.emit(currentPage() + 1)"
        >
          <span class="pagination__icon pagination__icon--next" aria-hidden="true"></span>
        </button>
      </div>
    </nav>
  `,
  styles: [`:host { display: block; }`],
})
export class PaginationComponent {
  currentPage = input.required<number>();
  totalPages = input.required<number>();
  pageSize = input<number>(10);
  pageSizeOptions = input<number[]>([10, 25, 50, 100]);
  loading = input<boolean>(false);
  customClass = input<string>('', { alias: 'class' });
  pageChanged = output<number>();
  pageSizeChanged = output<number>();

  isFirstPage = computed(() => this.currentPage() <= 1);
  isLastPage = computed(() => this.currentPage() >= this.totalPages());

  classes = computed(() => {
    const c = ['pagination'];
    if (this.loading()) c.push('pagination--loading');
    return c.join(' ');
  });

  onPageSizeSelect(event: Event): void {
    const value = Number((event.target as HTMLSelectElement).value);
    this.pageSizeChanged.emit(value);
  }
}
