// packages/components-vue/src/atoms/navigation/SegmentControl.vue
<script setup lang="ts">
/**
 * SegmentControl (Atom)
 *
 * Tabbed selection control with sliding indicator.
 * Supports disabled items.
 *
 * Data Attributes (Animation Contract):
 * - data-segment-control: Root element (discovery)
 * - data-segment-index: Index of each segment item
 *
 * Usage:
 * <SegmentControl :items="[{label:'Tab 1'},{label:'Tab 2'}]" v-model:selected-index="active" />
 *
 * @see packages/css/src/components/segment-control.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { Size } from '../../types'
import type { SegmentControlItem } from '../../types/segment-control'

interface SegmentControlProps {
  items: SegmentControlItem[]
  size?: Size
  selectedIndex?: number
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<SegmentControlProps>(), {
  size: 'm',
  selectedIndex: 0
})

const emit = defineEmits<{
  'update:selectedIndex': [index: number]
}>()

const segmentClasses = computed(() => [
  'segment-control',
  `segment-control--${props.size}`,
  props.class
])

const indicatorStyle = computed(() => ({
  '--segment-index': props.selectedIndex,
  '--segment-count': props.items.length
}))

function handleClick(index: number, isDisabled: boolean) {
  if (!isDisabled) {
    emit('update:selectedIndex', index)
  }
}

function handleKeyDown(index: number, isDisabled: boolean, event: KeyboardEvent) {
  if ((event.key === 'Enter' || event.key === ' ') && !isDisabled) {
    event.preventDefault()
    emit('update:selectedIndex', index)
  }
}
</script>

<template>
  <div
    :class="segmentClasses"
    data-segment-control
    role="tablist"
  >
    <span
      class="segment-control__indicator"
      :style="indicatorStyle"
    />
    <button
      v-for="(item, index) in items"
      :key="index"
      type="button"
      :class="[
        'segment-control__item',
        {
          'segment-control__item--selected': index === selectedIndex,
          'segment-control__item--disabled': !!item.disabled
        }
      ]"
      role="tab"
      :aria-selected="index === selectedIndex"
      :data-segment-index="index"
      :disabled="!!item.disabled"
      :tabindex="index === selectedIndex ? 0 : -1"
      @click="handleClick(index, !!item.disabled)"
      @keydown="handleKeyDown(index, !!item.disabled, $event)"
    >
      <span class="segment-control__label">{{ item.label }}</span>
    </button>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/navigation/segment-control.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

export interface SegmentControlItem {
  label: string;
  disabled?: boolean;
}

/**
 * Tabbed selection control with sliding indicator.
 *
 * @example
 * <atom-segment-control [items]="tabs" [selectedIndex]="0" (indexChanged)="onTab($event)"></atom-segment-control>
 *
 * @see packages/css/src/components/segment-control.css
 */
@Component({
  selector: 'atom-segment-control',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div
      [class]="classes()"
      data-segment-control
      role="tablist"
    >
      <span
        class="segment-control__indicator"
        [style.--segment-index]="selectedIndex()"
        [style.--segment-count]="items().length"
      ></span>
      @for (item of items(); track $index) {
        @let isSelected = $index === selectedIndex();
        @let isDisabled = !!item.disabled;
        <button
          type="button"
          [class]="itemClasses(isSelected, isDisabled)"
          role="tab"
          [attr.aria-selected]="isSelected"
          [attr.data-segment-index]="$index"
          [disabled]="isDisabled"
          [attr.tabindex]="isSelected ? 0 : -1"
          (click)="handleClick($index, isDisabled)"
        >
          <span class="segment-control__label">{{ item.label }}</span>
        </button>
      }
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class SegmentControlComponent {
  items = input.required<SegmentControlItem[]>();
  size = input<'xs' | 's' | 'm' | 'l' | 'xl'>('m');
  selectedIndex = input<number>(0);
  customClass = input<string>('', { alias: 'class' });
  indexChanged = output<number>();

  classes = computed(() => {
    return ['segment-control', `segment-control--${this.size()}`].join(' ');
  });

  itemClasses(isSelected: boolean, isDisabled: boolean): string {
    const c = ['segment-control__item'];
    if (isSelected) c.push('segment-control__item--selected');
    if (isDisabled) c.push('segment-control__item--disabled');
    return c.join(' ');
  }

  handleClick(index: number, disabled: boolean): void {
    if (!disabled) {
      this.indexChanged.emit(index);
    }
  }
}
