// packages/components-vue/src/atoms/buttons/LinkButton.vue
<script setup lang="ts">
/**
 * LinkButton (Atom)
 *
 * Text link styled as a button with optional icon support.
 * Single visual style (no variant), two sizes.
 *
 * Data Attributes (Animation Contract):
 * - data-link-button: Root element (discovery)
 * - data-shimmer: On loading text (shimmer animation)
 * - data-link-button-spinner: Loading spinner
 *
 * Usage:
 * <LinkButton size="l" href="/about">Learn more</LinkButton>
 * <LinkButton size="s" :is-loading="true">Loading...</LinkButton>
 *
 * @see packages/css/src/components/link-button.css
 */

import { computed, type HTMLAttributes } from 'vue'

type LinkButtonSize = 's' | 'l'

interface LinkButtonProps {
  size?: LinkButtonSize
  href?: string
  isDisabled?: boolean
  isLoading?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<LinkButtonProps>(), {
  size: 'l',
  isDisabled: false,
  isLoading: false
})

const isDisabled = computed(() => props.isDisabled || props.isLoading)

const linkButtonClasses = computed(() => [
  'link-button',
  `link-button--${props.size}`,
  {
    'link-button--disabled': isDisabled.value,
    'link-button--loading': props.isLoading
  },
  props.class
])
</script>

<template>
  <a
    :href="href"
    :class="linkButtonClasses"
    data-link-button
    :tabindex="isDisabled ? -1 : 0"
    :aria-disabled="isDisabled ? 'true' : undefined"
    :aria-busy="isLoading ? 'true' : undefined"
  >
    <span v-if="isLoading" class="link-button__loading-content">
      <span class="link-button__loading-text" data-shimmer>Loading</span>
      <span class="link-button__spinner" data-link-button-spinner aria-hidden="true" />
    </span>

    <span v-else class="link-button__label">
      <span v-if="$slots.iconLeft" class="link-button__icon">
        <slot name="iconLeft" />
      </span>
      <slot />
      <span v-if="$slots.iconRight" class="link-button__icon">
        <slot name="iconRight" />
      </span>
    </span>
  </a>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/buttons/link-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';

/**
 * Text link styled as a button with optional icon support.
 * Single visual style (no variant), two sizes.
 *
 * @example
 * <atom-link-button href="/docs" size="l">Read more</atom-link-button>
 *
 * @see packages/css/src/components/link-button.css
 */
@Component({
  selector: 'atom-link-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
    '[attr.data-link-button]': '""',
  },
  template: `
    @let isDisabled = isDisabledOrLoading();

    <a
      [href]="href()"
      [class]="classes()"
      [attr.tabindex]="isDisabled ? -1 : 0"
      [attr.aria-disabled]="isDisabled ? 'true' : null"
      [attr.aria-busy]="loading() ? 'true' : null"
      (click)="handleClick($event)"
    >
      @if (loading()) {
        <span class="link-button__loading-content">
          <span class="link-button__loading-text" data-shimmer>Loading</span>
          <span class="link-button__spinner" data-link-button-spinner aria-hidden="true"></span>
        </span>
      } @else {
        <span class="link-button__label">
          <ng-content select="[slot=icon-left]" />
          <ng-content />
          <ng-content select="[slot=icon-right]" />
        </span>
      }
    </a>
  `,
  styles: [`
    :host { display: inline-block; }
    a {
      all: unset;
      box-sizing: border-box;
      display: inline-flex;
      cursor: pointer;
      text-decoration: none;
    }
    a[aria-disabled="true"] { cursor: not-allowed; }
  `],
})
export class LinkButtonComponent {
  size = input<'s' | 'l'>('l');
  href = input<string>();
  disabled = input<boolean>(false);
  loading = input<boolean>(false);
  customClass = input<string>('', { alias: 'class' });
  clicked = output<MouseEvent>();

  isDisabledOrLoading = computed(() => this.disabled() || this.loading());

  classes = computed(() => {
    const c = [
      'link-button',
      `link-button--${this.size()}`,
    ];
    if (this.disabled()) c.push('link-button--disabled');
    if (this.loading()) c.push('link-button--loading');
    return c.join(' ');
  });

  handleClick(event: MouseEvent): void {
    if (this.isDisabledOrLoading()) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }
    this.clicked.emit(event);
  }
}
