// packages/components-vue/src/atoms/lists/BulletItem.vue
<script setup lang="ts">
/**
 * BulletItem (Atom)
 *
 * A list item for unordered bullet lists.
 * Renders as a semantic li element.
 *
 * Usage:
 * <ul>
 *   <BulletItem>First item</BulletItem>
 *   <BulletItem>Second item</BulletItem>
 * </ul>
 *
 * @see packages/css/src/components/lists.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface BulletItemProps {
  class?: HTMLAttributes['class']
}

const props = defineProps<BulletItemProps>()

const bulletClasses = computed(() => ['bullet-item', props.class])
</script>

<template>
  <li :class="bulletClasses">
    <slot />
  </li>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/lists/bullet-item.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
} from '@angular/core';

/**
 * A list item for unordered bullet lists.
 *
 * @example
 * <ul>
 *   <atom-bullet-item>First item</atom-bullet-item>
 *   <atom-bullet-item>Second item</atom-bullet-item>
 * </ul>
 *
 * @see packages/css/src/components/lists.css
 */
@Component({
  selector: 'atom-bullet-item',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <li class="bullet-item">
      <ng-content />
    </li>
  `,
  styles: [`:host { display: list-item; }`],
})
export class BulletItemComponent {
  customClass = input<string>('', { alias: 'class' });
}
