// packages/components-vue/src/atoms/indicators/EmptyState.vue
<script setup lang="ts">
/**
 * EmptyState (Atom)
 *
 * A placeholder component for empty content areas.
 * Displays heading, supporting text, optional result text, icon, and action slots.
 *
 * Usage:
 * <EmptyState heading="No results" supporting-text="Try a different search">
 *   <template #icon><SearchIcon /></template>
 *   <Button>Try Again</Button>
 * </EmptyState>
 *
 * @see packages/css/src/components/empty-state.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { EmptyStateSize } from '../../types/empty-state'

interface EmptyStateProps {
  size?: EmptyStateSize
  heading?: string
  supportingText?: string
  resultText?: string
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<EmptyStateProps>(), {
  size: 'm'
})

const classes = computed(() => [
  'empty-state',
  `empty-state--${props.size}`,
  props.class
])
</script>

<template>
  <div :class="classes">
    <div v-if="$slots.icon" class="empty-state__icon">
      <slot name="icon" />
    </div>
    <h3 v-if="heading" class="empty-state__heading">{{ heading }}</h3>
    <p v-if="supportingText" class="empty-state__supporting-text">{{ supportingText }}</p>
    <p v-if="resultText" class="empty-state__result-text">{{ resultText }}</p>
    <div v-if="$slots.default" class="empty-state__actions">
      <slot />
    </div>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/indicators/empty-state.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type EmptyStateSize = 's' | 'm';

/**
 * A placeholder component for empty content areas.
 * Displays heading, supporting text, optional result text, and action slots.
 *
 * @example
 * <atom-empty-state heading="No results" supportingText="Try a different search.">
 *   <atom-button variant="Secondary">Reset filters</atom-button>
 * </atom-empty-state>
 *
 * @see packages/css/src/components/empty-state.css
 */
@Component({
  selector: 'atom-empty-state',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <div [class]="classes()">
      <ng-content select="[slot=icon]" />
      @if (heading()) {
        <h3 class="empty-state__heading">{{ heading() }}</h3>
      }
      @if (supportingText()) {
        <p class="empty-state__supporting-text">{{ supportingText() }}</p>
      }
      @if (resultText()) {
        <p class="empty-state__result-text">{{ resultText() }}</p>
      }
      <div class="empty-state__actions">
        <ng-content />
      </div>
    </div>
  `,
  styles: [`:host { display: block; }`],
})
export class EmptyStateComponent {
  size = input<EmptyStateSize>('m');
  heading = input<string>();
  supportingText = input<string>();
  resultText = input<string>();
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    return ['empty-state', `empty-state--${this.size()}`].join(' ');
  });
}
