// packages/components-vue/src/atoms/indicators/Tag.vue
<script setup lang="ts">
/**
 * Tag (Atom)
 *
 * A non-interactive label for categorization and metadata display.
 * Supports filled/outlined variants and semantic color states.
 *
 * Data Attributes (Animation Contract):
 * - data-tag: Root element (discovery)
 *
 * Usage:
 * <Tag variant="filled" color="success">Active</Tag>
 * <Tag variant="outlined" color="warning" size="s">Beta</Tag>
 *
 * @see packages/css/src/components/tag.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { TagVariant, TagColor, TagSize } from '../../types/tag'

interface TagProps {
  variant?: TagVariant
  color?: TagColor
  size?: TagSize
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<TagProps>(), {
  variant: 'filled',
  color: 'default',
  size: 'm'
})

const tagClasses = computed(() => [
  'tag',
  `tag--${props.variant}`,
  `tag--${props.color}`,
  `tag--${props.size}`,
  props.class
])
</script>

<template>
  <span :class="tagClasses" data-tag>
    <slot />
  </span>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-angular/src/atoms/indicators/tag.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type TagVariant = 'filled' | 'outlined';
export type TagColor = 'default' | 'info' | 'success' | 'warning' | 'error';
export type TagSize = 's' | 'm' | 'l';

/**
 * A non-interactive label for categorization and metadata display.
 *
 * @example
 * <atom-tag variant="filled" color="success" size="m">Active</atom-tag>
 *
 * @see packages/css/src/components/tag.css
 */
@Component({
  selector: 'atom-tag',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <span [class]="classes()" data-tag>
      <ng-content />
    </span>
  `,
  styles: [`:host { display: inline-block; }`],
})
export class TagComponent {
  variant = input<TagVariant>('filled');
  color = input<TagColor>('default');
  size = input<TagSize>('m');
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    return [
      'tag',
      `tag--${this.variant()}`,
      `tag--${this.color()}`,
      `tag--${this.size()}`,
    ].join(' ');
  });
}
