// packages/components-vue/src/molecules/Accordion.vue
<script setup lang="ts">
/**
 * Accordion (Molecule)
 *
 * Expandable content panels with CSS grid animation.
 * Supports single-open (close siblings) and multi-open modes.
 *
 * Data Attributes (Animation Contract):
 * - data-accordion: Root element (discovery)
 * - data-accordion-close-siblings: Whether siblings auto-close
 * - data-accordion-status: 'open' | 'closed' per item
 * - data-accordion-toggle: Clickable header
 *
 * Usage:
 * <Accordion :items="items" :close-siblings="true">
 *   <template #item-content="{ item, index }">
 *     <p>{{ item.title }} content here</p>
 *   </template>
 * </Accordion>
 *
 * @see packages/css/src/components/accordion.css
 */

import { computed, ref, type HTMLAttributes } from 'vue'
import type { AccordionItem } from '../types/accordion'

interface AccordionProps {
  items: AccordionItem[]
  closeSiblings?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<AccordionProps>(), {
  closeSiblings: true
})

// Build initial open state from items
const openMap = ref<Record<number, boolean>>(
  (() => {
    const map: Record<number, boolean> = {}
    props.items.forEach((item, i) => {
      if (item.open) map[i] = true
    })
    return map
  })()
)

function handleToggle(index: number) {
  if (props.closeSiblings) {
    openMap.value = openMap.value[index] ? {} : { [index]: true }
  } else {
    openMap.value = { ...openMap.value, [index]: !openMap.value[index] }
  }
}

function handleKeyDown(index: number, event: KeyboardEvent) {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    handleToggle(index)
  }
}

const accordionClasses = computed(() => [
  'accordion',
  props.class
])

function getItemId(item: AccordionItem, index: number): string {
  return item.id || `accordion-item-${index}`
}
</script>

<template>
  <div
    :class="accordionClasses"
    data-accordion
    :data-accordion-close-siblings="closeSiblings || undefined"
  >
    <div class="accordion__list">
      <div
        v-for="(item, index) in items"
        :key="getItemId(item, index)"
        class="accordion__item"
        :data-accordion-status="openMap[index] ? 'open' : 'closed'"
      >
        <div
          class="accordion__header"
          role="button"
          tabindex="0"
          :aria-expanded="!!openMap[index]"
          :aria-controls="`${getItemId(item, index)}-body`"
          :id="`${getItemId(item, index)}-header`"
          data-accordion-toggle
          @click="handleToggle(index)"
          @keydown="handleKeyDown(index, $event)"
        >
          <span class="accordion__title">{{ item.title }}</span>
          <svg
            class="accordion__icon"
            viewBox="0 0 16 16"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <path d="M4 6l4 4 4-4" />
          </svg>
        </div>
        <div
          class="accordion__body"
          :id="`${getItemId(item, index)}-body`"
          role="region"
          :aria-labelledby="`${getItemId(item, index)}-header`"
        >
          <div class="accordion__body-wrap">
            <div class="accordion__body-content">
              <slot name="item-content" :item="item" :index="index" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/molecules/Accordion.tsx
/**
 * Accordion (Molecule)
 *
 * CSS-driven expand/collapse via grid-template-rows.
 * State managed in React — no dependency on initAccordion().
 * HTML structure matches Astro component 1:1.
 *
 * CSS contract:
 *   [data-accordion-status="active"]   → expanded
 *   [data-accordion-status="not-active"] → collapsed
 *
 * @see packages/css/src/components/containers/accordion.css
 * @see packages/components-astro/src/molecules/Accordion.astro
 */

import { forwardRef, useState, useId, useCallback, type HTMLAttributes, type ReactNode } from 'react';
import { cn } from '../utils/cn';

export interface AccordionItem {
  title: string;
  content: ReactNode;
  open?: boolean;
  id?: string;
}

export interface AccordionProps extends HTMLAttributes<HTMLDivElement> {
  items: AccordionItem[];
  closeSiblings?: boolean;
}

// Hoisted — matches Astro's SVG exactly
const ChevronIcon = (
  <div className="accordion__icon" aria-hidden="true">
    <svg
      className="accordion__icon-svg"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 36 36"
      fill="none"
    >
      <path
        d="M28.5 22.5L18 12L7.5 22.5"
        stroke="currentColor"
        strokeWidth="3"
        strokeMiterlimit="10"
      />
    </svg>
  </div>
);

export const Accordion = forwardRef<HTMLDivElement, AccordionProps>(
  ({ items, closeSiblings = true, className, ...rest }, ref) => {
    const uid = useId();

    const [openMap, setOpenMap] = useState<Record<number, boolean>>(() => {
      const map: Record<number, boolean> = {};
      items.forEach((item, i) => { if (item.open) map[i] = true; });
      return map;
    });

    const handleToggle = useCallback((index: number) => {
      setOpenMap((prev) => {
        if (closeSiblings) return prev[index] ? {} : { [index]: true };
        return { ...prev, [index]: !prev[index] };
      });
    }, [closeSiblings]);

    const handleKeyDown = useCallback((index: number, e: React.KeyboardEvent) => {
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        handleToggle(index);
      }
    }, [handleToggle]);

    return (
      <div
        ref={ref}
        className={cn('accordion', className)}
        data-accordion
        data-accordion-close-siblings={closeSiblings.toString()}
        {...rest}
      >
        <ul className="accordion__list">
          {items.map((item, index) => {
            const isOpen = !!openMap[index];
            const itemId = item.id ?? `accordion-${uid}-${index}`;
            const bodyId = `${itemId}-body`;

            return (
              <li
                key={itemId}
                className="accordion__item"
                data-accordion-status={isOpen ? 'active' : 'not-active'}
                id={itemId}
              >
                <div
                  className="accordion__header"
                  role="button"
                  tabIndex={0}
                  aria-expanded={isOpen}
                  aria-controls={bodyId}
                  data-accordion-toggle
                  onClick={() => handleToggle(index)}
                  onKeyDown={(e) => handleKeyDown(index, e)}
                >
                  <h3 className="accordion__title">{item.title}</h3>
                  {ChevronIcon}
                </div>
                <div
                  className="accordion__body"
                  id={bodyId}
                  role="region"
                  aria-labelledby={itemId}
                >
                  <div className="accordion__body-wrap">
                    <div className="accordion__body-content">
                      {typeof item.content === 'string'
                        ? <p>{item.content}</p>
                        : item.content}
                    </div>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
);

Accordion.displayName = 'Accordion';
