// packages/components-vue/src/molecules/AvatarGroup.vue
<script setup lang="ts">
/**
 * AvatarGroup (Molecule)
 *
 * Displays multiple avatars in a stacked layout with an overflow counter.
 * Uses Avatar internally for consistent rendering.
 *
 * Data Attributes (Animation Contract):
 * - data-avatar-group: Root element (discovery)
 * - data-size: Avatar size
 * - data-shape: Avatar shape
 * - data-avatar-group-overflow: Overflow counter
 *
 * Usage:
 * <AvatarGroup :avatars="[{src: '/a.jpg'}, {initials: 'JD'}]" :max="3" size="s" />
 *
 * @see packages/css/src/components/avatar-group.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { AvatarSize, AvatarShape, AvatarGroupItem } from '../types/avatar-group'
import Avatar from '../atoms/media/Avatar.vue'

interface AvatarGroupProps {
  avatars: AvatarGroupItem[]
  max?: number
  size?: AvatarSize
  shape?: AvatarShape
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<AvatarGroupProps>(), {
  max: 5,
  size: 'xs',
  shape: 'circle'
})

const visible = computed(() => props.avatars.slice(0, props.max))
const overflow = computed(() => props.avatars.length - props.max)

const groupClasses = computed(() => [
  'avatar-group',
  `avatar-group--${props.size}`,
  `avatar-group--${props.shape}`,
  props.class
])
</script>

<template>
  <div
    v-if="avatars && avatars.length > 0"
    :class="groupClasses"
    data-avatar-group
    :data-size="size"
    :data-shape="shape"
    role="group"
    :aria-label="`Group of ${avatars.length} avatars`"
  >
    <Avatar
      v-for="(avatar, index) in visible"
      :key="index"
      :src="avatar.src"
      :initials="avatar.initials"
      :alt="avatar.alt || ''"
      :size="size"
      :shape="shape"
      class="avatar-group__item"
    />
    <span
      v-if="overflow > 0"
      class="avatar-group__overflow"
      data-avatar-group-overflow
      :aria-label="`${overflow} more`"
    >
      +{{ overflow }}
    </span>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/molecules/AvatarGroup.tsx
/**
 * AvatarGroup (Molecule)
 *
 * Displays multiple avatars in a stacked layout with an overflow counter.
 * Composes Avatar atoms. Shared props (size, shape, type) applied to all items.
 * Per-item badge supported individually.
 *
 * HTML structure matches Astro component 1:1.
 *
 * @see packages/css/src/components/avatar-group.css
 * @see packages/components-astro/src/molecules/AvatarGroup.astro
 */

import { forwardRef, type HTMLAttributes } from 'react';
import type { AvatarSize, AvatarShape, AvatarType, StatusType } from '../types';
import { cn } from '../utils/cn';
import { Avatar } from '../atoms/Avatar';

export interface AvatarGroupItem {
  src?: string;
  alt?: string;
  initials?: string;
  badge?: StatusType;
}

export interface AvatarGroupProps extends HTMLAttributes<HTMLDivElement> {
  avatars: AvatarGroupItem[];
  max?: number;
  size?: AvatarSize;
  shape?: AvatarShape;
  type?: AvatarType;
}

export const AvatarGroup = forwardRef<HTMLDivElement, AvatarGroupProps>(
  (
    {
      avatars,
      max = 5,
      size = 's',
      shape = 'circle',
      type = 'image-border',
      className,
      ...rest
    },
    ref
  ) => {
    if (!avatars || avatars.length === 0) return null;

    const visible = avatars.slice(0, max);
    const remainingCount = Math.max(0, avatars.length - max);
    const showCounter = remainingCount > 0;

    return (
      <div
        ref={ref}
        className={cn('avatar-group', `avatar-group--${size}`, className)}
        data-avatar-group
        data-size={size}
        data-shape={shape}
        data-type={type}
        role="group"
        aria-label={`${avatars.length} ${avatars.length === 1 ? 'member' : 'members'}`}
        {...rest}
      >
        {visible.map((avatar, index) => (
          <Avatar
            key={index}
            src={avatar.src}
            alt={avatar.alt ?? ''}
            initials={avatar.initials}
            size={size}
            shape={shape}
            type={avatar.src ? type : 'initials'}
            badge={avatar.badge ?? 'none'}
            className="avatar-group__item"
            data-avatar-index={index}
          />
        ))}

        {showCounter && (
          <span
            className="avatar-group__counter"
            data-avatar-counter
            role="status"
            aria-label={`${remainingCount} more ${remainingCount === 1 ? 'member' : 'members'}`}
          >
            +{remainingCount}
          </span>
        )}
      </div>
    );
  }
);

AvatarGroup.displayName = 'AvatarGroup';
