// packages/components-vue/src/molecules/CardBody.vue
<script setup lang="ts">
/**
 * CardBody (Molecule -- Card subcomponent)
 *
 * Body section of a Card with headline, subhead, text, and custom content.
 *
 * Data Attributes (Animation Contract):
 * - data-card-body: Root element
 * - data-card-body-headline: Headline text
 * - data-card-body-subhead: Subhead text
 * - data-card-body-text: Body text
 *
 * Usage:
 * <CardBody headline="Title" subhead="Subtitle" text="Body content here" />
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface CardBodyProps {
  headline?: string
  subhead?: string
  text?: string
  class?: HTMLAttributes['class']
}

const props = defineProps<CardBodyProps>()

const bodyClasses = computed(() => ['card__body', props.class])
</script>

<template>
  <div :class="bodyClasses" data-card-body>
    <span v-if="headline" class="card__body-headline" data-card-body-headline>
      {{ headline }}
    </span>
    <span v-if="subhead" class="card__body-subhead" data-card-body-subhead>
      {{ subhead }}
    </span>
    <p v-if="text" class="card__body-text" data-card-body-text>
      {{ text }}
    </p>
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/molecules/CardBody.tsx
/**
 * CardBody (Molecule — Card subcomponent)
 *
 * Body section of a Card. Accepts headline/subhead props or custom children.
 * When children are passed they render inside card-body__content wrapper.
 * HTML matches Astro component 1:1.
 *
 * @see packages/css/src/components/card.css
 * @see packages/components-astro/src/molecules/CardBody.astro
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../utils/cn';

export interface CardBodyProps extends HTMLAttributes<HTMLDivElement> {
  headline?: string;
  subhead?: string;
  bodyText?: string;
}

export const CardBody = forwardRef<HTMLDivElement, CardBodyProps>(
  ({ headline, subhead, bodyText, className, children, ...rest }, ref) => {
    const showHeadGroup = headline || subhead;

    return (
      <div ref={ref} className={cn('card-body', className)} {...rest}>
        {showHeadGroup && (
          <div className="card-body__head">
            {headline && <h4 className="card-body__headline">{headline}</h4>}
            {subhead && <p className="card-body__subhead">{subhead}</p>}
          </div>
        )}

        {children ? (
          <div className="card-body__content">
            {children}
          </div>
        ) : bodyText ? (
          <p className="card-body__text">{bodyText}</p>
        ) : null}
      </div>
    );
  }
);

CardBody.displayName = 'CardBody';
