// packages/components-vue/src/molecules/CardHeader.vue
<script setup lang="ts">
/**
 * CardHeader (Molecule -- Card subcomponent)
 *
 * Header section of a Card with avatar, headline, supporting text, and action slot.
 *
 * Data Attributes (Animation Contract):
 * - data-card-header: Root element
 * - data-card-avatar: Avatar wrapper
 * - data-card-headline: Headline text
 * - data-card-supporting: Supporting text
 * - data-card-action: Action slot wrapper
 *
 * Usage:
 * <CardHeader headline="Card Title" supporting="Subtitle text">
 *   <template #avatar><Avatar initials="JD" /></template>
 *   <template #action><IconButton aria-label="More" /></template>
 * </CardHeader>
 *
 * @see packages/css/src/components/card.css
 */

import { computed, type HTMLAttributes } from 'vue'

interface CardHeaderProps {
  headline?: string
  supporting?: string
  class?: HTMLAttributes['class']
}

const props = defineProps<CardHeaderProps>()

const headerClasses = computed(() => ['card__header', props.class])
</script>

<template>
  <div :class="headerClasses" data-card-header>
    <div v-if="$slots.avatar" class="card__header-avatar" data-card-avatar>
      <slot name="avatar" />
    </div>
    <div class="card__header-text">
      <span v-if="headline" class="card__header-headline" data-card-headline>
        {{ headline }}
      </span>
      <span v-if="supporting" class="card__header-supporting" data-card-supporting>
        {{ supporting }}
      </span>
    </div>
    <div v-if="$slots.action" class="card__header-action" data-card-action>
      <slot name="action" />
    </div>
    <slot />
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/molecules/CardHeader.tsx
/**
 * CardHeader (Molecule — Card subcomponent)
 *
 * Header section of a Card with optional image/avatar, headline,
 * supporting text, and action slot.
 * HTML matches Astro component 1:1.
 *
 * @see packages/css/src/components/card.css
 * @see packages/components-astro/src/molecules/CardHeader.astro
 */

import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { cn } from '../utils/cn';

export interface CardHeaderProps extends HTMLAttributes<HTMLDivElement> {
  headline: string;
  supportingText?: string;
  image?: ReactNode;   // slot="image" equivalent
  action?: ReactNode;  // slot="action" equivalent
}

export const CardHeader = forwardRef<HTMLDivElement, CardHeaderProps>(
  ({ headline, supportingText, image, action, className, ...rest }, ref) => (
    <div ref={ref} className={cn('card-header', className)} {...rest}>
      <div className="card-header__content">
        {image && (
          <div className="card-header__image">
            {image}
          </div>
        )}
        <div className="card-header__text">
          <h3 className="card-header__headline">{headline}</h3>
          {supportingText && (
            <p className="card-header__supporting">{supportingText}</p>
          )}
        </div>
      </div>

      {action && (
        <div className="card-header__action">
          {action}
        </div>
      )}
    </div>
  )
);

CardHeader.displayName = 'CardHeader';
