// packages/components-vue/src/atoms/navigation/SegmentControl.vue
<script setup lang="ts">
/**
 * SegmentControl (Atom)
 *
 * Tabbed selection control with sliding indicator.
 * Supports disabled items.
 *
 * Data Attributes (Animation Contract):
 * - data-segment-control: Root element (discovery)
 * - data-segment-index: Index of each segment item
 *
 * Usage:
 * <SegmentControl :items="[{label:'Tab 1'},{label:'Tab 2'}]" v-model:selected-index="active" />
 *
 * @see packages/css/src/components/segment-control.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { Size } from '../../types'
import type { SegmentControlItem } from '../../types/segment-control'

interface SegmentControlProps {
  items: SegmentControlItem[]
  size?: Size
  selectedIndex?: number
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<SegmentControlProps>(), {
  size: 'm',
  selectedIndex: 0
})

const emit = defineEmits<{
  'update:selectedIndex': [index: number]
}>()

const segmentClasses = computed(() => [
  'segment-control',
  `segment-control--${props.size}`,
  props.class
])

const indicatorStyle = computed(() => ({
  '--segment-index': props.selectedIndex,
  '--segment-count': props.items.length
}))

function handleClick(index: number, isDisabled: boolean) {
  if (!isDisabled) {
    emit('update:selectedIndex', index)
  }
}

function handleKeyDown(index: number, isDisabled: boolean, event: KeyboardEvent) {
  if ((event.key === 'Enter' || event.key === ' ') && !isDisabled) {
    event.preventDefault()
    emit('update:selectedIndex', index)
  }
}
</script>

<template>
  <div
    :class="segmentClasses"
    data-segment-control
    role="tablist"
  >
    <span
      class="segment-control__indicator"
      :style="indicatorStyle"
    />
    <button
      v-for="(item, index) in items"
      :key="index"
      type="button"
      :class="[
        'segment-control__item',
        {
          'segment-control__item--selected': index === selectedIndex,
          'segment-control__item--disabled': !!item.disabled
        }
      ]"
      role="tab"
      :aria-selected="index === selectedIndex"
      :data-segment-index="index"
      :disabled="!!item.disabled"
      :tabindex="index === selectedIndex ? 0 : -1"
      @click="handleClick(index, !!item.disabled)"
      @keydown="handleKeyDown(index, !!item.disabled, $event)"
    >
      <span class="segment-control__label">{{ item.label }}</span>
    </button>
  </div>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/atoms/navigation/SegmentControl.tsx
/**
 * SegmentControl (Atom)
 *
 * Tabbed selection control with icon, label and info support.
 * HTML output mirrors the Astro component exactly.
 *
 * Performance optimizations:
 * - forwardRef for ref forwarding
 * - No inline component definitions (rerender-no-inline-components)
 *
 * @see packages/css/src/components/navigation/segment-control.css
 * @see packages/tokens/src/components/navigation/segment-control.json
 */

import { forwardRef, type HTMLAttributes, type ReactNode } from 'react';
import { cn } from '../../utils/cn';

// ── SegmentControl Item ───────────────────────────────────
export interface SegmentControlItem {
  label?: string;
  icon?: ReactNode;
  info?: ReactNode;
  disabled?: boolean;
}

// ── SegmentControl Props ──────────────────────────────────
export interface SegmentControlProps extends Omit<HTMLAttributes<HTMLDivElement>, 'onChange'> {
  items: SegmentControlItem[];
  size?: 'xs' | 's' | 'm' | 'l' | 'xl';
  selectedIndex?: number;
  disabled?: boolean;
  name?: string;
  onChange?: (index: number) => void;
}

// ── SegmentControl Component ──────────────────────────────
export const SegmentControl = forwardRef<HTMLDivElement, SegmentControlProps>(
  (props, ref) => {
    const {
      items,
      size = 'm',
      selectedIndex = 0,
      disabled = false,
      name,
      onChange,
      className,
      ...rest
    } = props;

    return (
      <div
        ref={ref}
        className={cn('segment-control', `segment-control--${size}`, className)}
        role="tablist"
        aria-label={name}
        data-segment-control
        {...rest}
      >
        {items.map((item, index) => {
          const isSelected = index === selectedIndex;
          const isDisabled = disabled || !!item.disabled;

          return (
            <button
              key={index}
              type="button"
              className={cn(
                'segment-control__item',
                isSelected && 'segment-control__item--selected',
                isDisabled && 'segment-control__item--disabled'
              )}
              role="tab"
              aria-selected={isSelected}
              aria-disabled={isDisabled || undefined}
              data-segment-index={index}
              disabled={isDisabled}
              tabIndex={isSelected ? 0 : -1}
              onClick={() => {
                if (!isDisabled) onChange?.(index);
              }}
            >
              <div className="segment-control__content">
                {item.icon && (
                  <span className="segment-control__icon" aria-hidden="true">
                    {item.icon}
                  </span>
                )}
                {item.label && (
                  <span className="segment-control__label">{item.label}</span>
                )}
                {item.info && (
                  <span className="segment-control__info" aria-hidden="true">
                    {item.info}
                  </span>
                )}
              </div>
            </button>
          );
        })}
      </div>
    );
  }
);

SegmentControl.displayName = 'SegmentControl';
