// packages/components-vue/src/atoms/buttons/NavLink.vue
<script setup lang="ts">
/**
 * NavLink (Atom)
 *
 * CSS-only underline link with animation support.
 * Supports two underline styles (default and alt) and multiple variants.
 *
 * Data Attributes (Animation Contract):
 * - data-underline-link: Underline style ('alt' or '')
 *
 * Usage:
 * <NavLink href="/about" variant="primary">About</NavLink>
 * <NavLink href="/contact" underline="alt" size="s">Contact</NavLink>
 *
 * @see packages/css/src/components/nav-link.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { NavLinkUnderline, NavLinkVariant } from '../../types/nav-link'
import type { Size } from '../../types'

interface NavLinkProps {
  href?: string
  underline?: NavLinkUnderline
  variant?: NavLinkVariant
  size?: Size
  isDisabled?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<NavLinkProps>(), {
  underline: 'default',
  variant: 'primary',
  size: 'm',
  isDisabled: false
})

const navLinkClasses = computed(() => [
  'nav-link',
  `nav-link--${props.variant}`,
  `nav-link--${props.size}`,
  {
    'nav-link--disabled': props.isDisabled
  },
  props.class
])
</script>

<template>
  <a
    :href="href"
    :class="navLinkClasses"
    :data-underline-link="underline === 'alt' ? 'alt' : ''"
    :tabindex="isDisabled ? -1 : 0"
    :aria-disabled="isDisabled ? 'true' : undefined"
  >
    <slot />
  </a>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->

// packages/components-react/src/atoms/buttons/NavLink.tsx
/**
 * NavLink (Atom)
 *
 * CSS-only underline link with animation support.
 * Supports two underline styles (default and alt) and multiple variants.
 *
 * Performance optimizations:
 * - forwardRef for ref forwarding
 * - No inline component definitions (rerender-no-inline-components)
 *
 * @see packages/css/src/components/nav-link.css
 * @see packages/tokens/src/components/nav-link.json
 */

import { forwardRef, type AnchorHTMLAttributes } from 'react';
import type { SizeVariant } from '../../types';
import { cn } from '../../utils/cn';

// ── NavLink Types ─────────────────────────────────────────
type NavLinkUnderline = 'default' | 'alt';
type NavLinkVariant = 'primary' | 'secondary' | 'tertiary' | 'inverse';

// ── NavLink Props ─────────────────────────────────────────
export interface NavLinkProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
  href?: string;
  underline?: NavLinkUnderline;
  variant?: NavLinkVariant;
  size?: SizeVariant;
  disabled?: boolean;
}

// ── NavLink Component ─────────────────────────────────────
export const NavLink = forwardRef<HTMLAnchorElement, NavLinkProps>(
  (props, ref) => {
    const {
      href,
      underline = 'default',
      variant = 'primary',
      size = 's',
      disabled = false,
      className,
      children,
      ...rest
    } = props;

    const classes = cn(
      'nav-link',
      `nav-link--${variant}`,
      `nav-link--${size}`,
      disabled && 'nav-link--disabled',
      className
    );

    return (
      <a
        ref={ref}
        href={disabled ? undefined : href}
        className={classes}
        data-underline-link={underline === 'alt' ? 'alt' : true}
        tabIndex={disabled ? -1 : undefined}
        aria-disabled={disabled ? true : undefined}
        {...rest}
      >
        {children}
      </a>
    );
  }
);

NavLink.displayName = 'NavLink';
