// packages/components-angular/src/atoms/indicators/badge.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type BadgeType = 'neutral' | 'inbox' | 'info';
export type BadgeState = 'default' | 'focused' | 'subtle';
export type BadgeContext = 'default' | 'inbox';

/**
 * Notification badge with smart overflow logic.
 * Displays notification counts with context-aware capping rules.
 *
 * @example
 * <atom-badge [count]="5" type="neutral"></atom-badge>
 *
 * @see packages/css/src/components/badge.css
 */
@Component({
  selector: 'atom-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    @let display = displayValue();
    @if (display) {
      <span
        [class]="classes()"
        data-badge
        [attr.data-count]="count()"
        [attr.data-context]="context()"
        [attr.data-state]="state()"
        role="status"
        [attr.aria-label]="ariaLabel()"
      >
        <span class="badge__text" data-badge-text>{{ display }}</span>
      </span>
    }
  `,
  styles: [`:host { display: inline-block; }`],
})
export class BadgeComponent {
  count = input<number>(0);
  context = input<BadgeContext>('default');
  type = input<BadgeType>('neutral');
  state = input<BadgeState>('default');
  customClass = input<string>('', { alias: 'class' });

  displayValue = computed(() => {
    const c = this.count();
    const ctx = this.context();
    if (c <= 0) return null;
    if (ctx === 'inbox') {
      return c >= 50 ? '+50' : c.toString();
    }
    return c > 99 ? '99+' : c.toString();
  });

  ariaLabel = computed(() => {
    const c = this.count();
    return `${c} ${c === 1 ? 'notification' : 'notifications'}`;
  });

  classes = computed(() => {
    return ['badge', `badge--${this.type()}`, `badge--${this.state()}`].join(' ');
  });
}

// packages/components-vue/src/atoms/indicators/Badge.vue
<script setup lang="ts">
/**
 * Badge (Atom)
 *
 * A notification indicator with smart overflow logic.
 * Displays notification counts with context-aware capping rules.
 *
 * Data Attributes (Animation Contract):
 * - data-badge: Root element (discovery)
 * - data-count: Raw count value
 * - data-context: Badge context ('default' | 'inbox')
 * - data-state: Badge state
 * - data-badge-text: Text content element
 *
 * Usage:
 * <Badge :count="5" />
 * <Badge :count="150" context="inbox" type="inbox" />
 *
 * @see packages/css/src/components/badge.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { BadgeType, BadgeState, BadgeContext } from '../../types/badge'

interface BadgeProps {
  count: number
  context?: BadgeContext
  type?: BadgeType
  state?: BadgeState
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<BadgeProps>(), {
  count: 0,
  context: 'default',
  type: 'neutral',
  state: 'default'
})

function getBadgeDisplay(count: number, context: BadgeContext): string | null {
  if (count <= 0) return null

  if (context === 'inbox') {
    if (count >= 50) return '+50'
    return count.toString()
  }

  if (count > 99) return '99+'
  return count.toString()
}

const displayValue = computed(() => getBadgeDisplay(props.count, props.context))

const ariaLabel = computed(
  () => `${props.count} ${props.count === 1 ? 'notification' : 'notifications'}`
)

const badgeClasses = computed(() => [
  'badge',
  `badge--${props.type}`,
  `badge--${props.state}`,
  props.class
])
</script>

<template>
  <span
    v-if="displayValue"
    :class="badgeClasses"
    data-badge
    :data-count="count"
    :data-context="context"
    :data-state="state"
    role="status"
    :aria-label="ariaLabel"
  >
    <span class="badge__text" data-badge-text>
      {{ displayValue }}
    </span>
  </span>
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
