// packages/components-angular/src/atoms/indicators/spinner.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';

export type SpinnerSize = 's' | 'm' | 'l';
export type SpinnerColor = 'primary' | 'inverse';

/**
 * A loading indicator with size and color variants.
 *
 * @example
 * <atom-spinner size="m" color="primary"></atom-spinner>
 *
 * @see packages/css/src/components/spinner.css
 */
@Component({
  selector: 'atom-spinner',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'customClass() || null',
  },
  template: `
    <span
      [class]="classes()"
      data-spinner
      role="status"
      aria-label="Loading"
    ></span>
  `,
  styles: [`:host { display: inline-block; }`],
})
export class SpinnerComponent {
  size = input<SpinnerSize>('m');
  color = input<SpinnerColor>('primary');
  customClass = input<string>('', { alias: 'class' });

  classes = computed(() => {
    return [
      'spinner',
      `spinner--${this.size()}`,
      `spinner--${this.color()}`,
    ].join(' ');
  });
}

// packages/components-vue/src/atoms/indicators/Spinner.vue
<script setup lang="ts">
/**
 * Spinner (Atom)
 *
 * A loading indicator with size and color variants.
 * Provides accessible loading state communication.
 *
 * Data Attributes (Animation Contract):
 * - data-spinner: Root element (discovery)
 *
 * Usage:
 * <Spinner size="m" color="primary" />
 * <Spinner size="l" color="inverse" />
 *
 * @see packages/css/src/components/spinner.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { SpinnerSize, SpinnerColor } from '../../types/spinner'

interface SpinnerProps {
  size?: SpinnerSize
  color?: SpinnerColor
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<SpinnerProps>(), {
  size: 'm',
  color: 'primary'
})

const spinnerClasses = computed(() => [
  'spinner',
  `spinner--${props.size}`,
  `spinner--${props.color}`,
  props.class
])
</script>

<template>
  <span
    :class="spinnerClasses"
    data-spinner
    role="status"
    aria-label="Loading"
  />
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
