// packages/components-react/src/atoms/indicators/Spinner.tsx
/**
 * Spinner (Atom)
 *
 * Loading indicator with continuous rotation animation.
 * HTML output mirrors the Astro component exactly.
 *
 * @see packages/css/src/components/indicators/spinner.css
 * @see packages/tokens/src/components/indicators/spinner.json
 */

import { forwardRef, type HTMLAttributes } from 'react';
import { cn } from '../../utils/cn';

export type SpinnerSize = 'xs' | 's' | 'm' | 'l' | 'xl';

export interface SpinnerProps extends HTMLAttributes<HTMLSpanElement> {
  size?: SpinnerSize;
}

export const Spinner = forwardRef<HTMLSpanElement, SpinnerProps>(
  ({ size = 'm', className, ...rest }, ref) => (
    <span
      ref={ref}
      className={cn('spinner', `spinner--${size}`, className)}
      role="status"
      aria-label="Loading"
      data-spinner
      {...rest}
    >
      <span className="spinner__track" />
      <span className="spinner__indicator" data-spinner-indicator />
    </span>
  )
);

Spinner.displayName = 'Spinner';

// packages/components-vue/src/atoms/indicators/Spinner.vue
<script setup lang="ts">
/**
 * Spinner (Atom)
 *
 * A loading indicator with size and color variants.
 * Provides accessible loading state communication.
 *
 * Data Attributes (Animation Contract):
 * - data-spinner: Root element (discovery)
 *
 * Usage:
 * <Spinner size="m" color="primary" />
 * <Spinner size="l" color="inverse" />
 *
 * @see packages/css/src/components/spinner.css
 */

import { computed, type HTMLAttributes } from 'vue'
import type { SpinnerSize, SpinnerColor } from '../../types/spinner'

interface SpinnerProps {
  size?: SpinnerSize
  color?: SpinnerColor
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<SpinnerProps>(), {
  size: 'm',
  color: 'primary'
})

const spinnerClasses = computed(() => [
  'spinner',
  `spinner--${props.size}`,
  `spinner--${props.color}`,
  props.class
])
</script>

<template>
  <span
    :class="spinnerClasses"
    data-spinner
    role="status"
    aria-label="Loading"
  />
</template>

<!-- NO <style> block — All styles from @atomchat.io/css -->
